### 与机器人聊天
POST http://localhost:8080/odata/v4/MainService/BotInstances(19ed1a3d-2054-4345-bc73-42502aedc648)/MainService.chatCompletion
Content-Type: application/json

{
  "content": "Test chatCompletion action"
}
###BotExecutionClass查询测试
GET http://localhost:8080/odata/v4/ConfigService/BotExecutionClass?$filter=contains(Description, 'Bot') 
Accept:application/json

### 测试TaskHierarchyView
GET  http://localhost:8080/odata/v4/MainService/TaskHierarchyView?$apply=descendants($root/TaskHierarchyView,TaskHierarchyView,ID,filter(contains(name,'FirstRAPReport')),keep start)
Authorization: Basic system:

### 获取TaskHierarchyView数据
GET  http://localhost:8080/odata/v4/MainService/TaskHierarchyView
Authorization: Basic system: