### 与机器人聊天
POST http://localhost:8080/odata/v4/MainService/BotInstances(19ed1a3d-2054-4345-bc73-42502aedc648)/MainService.chatCompletion
Content-Type: application/json

{
  "content": "Test chatCompletion action"
}
###BotExecutionClass查询测试
GET http://localhost:8080/odata/v4/ConfigService/BotExecutionClass?$filter=contains(Description, 'Bot') 
Accept:application/json

### 获取TaskHierarchy所有数据
GET  http://localhost:8080/odata/v4/MainService/TaskHierarchy
Authorization: Basic system:

### 获取TaskHierarchy根节点
GET  http://localhost:8080/odata/v4/MainService/TaskHierarchy?$select=ID,parent_ID,name&$apply=com.sap.vocabularies.Hierarchy.v1.TopLevels(HierarchyNodes=$root/TaskHierarchy,HierarchyQualifier='TaskHierarchy',NodeProperty='ID',Levels=1)
Authorization: Basic system:

### 获取TaskHierarchy根节点
GET  http://localhost:8080/odata/v4/MainService/TaskHierarchy?$apply=com.sap.vocabularies.Hierarchy.v1.TopLevels(HierarchyNodes=$root/TaskHierarchy,HierarchyQualifier='TaskHierarchy',NodeProperty='ID')
Authorization: Basic system:

### 获取TaskHierarchy某节点所有子节点
GET  http://localhost:8080/odata/v4/MainService/TaskHierarchy?$apply=descendants($root/TaskHierarchy,TaskHierarchy,ID,filter(ID eq 98eb493f-02fa-42cd-9f7d-1741c4575aec),keep start)
Authorization: Basic system:

