
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.services;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.ServiceWithNavigableEntities;
import com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData;
import lombok.Getter;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>s4_create_cds_metadata</td></tr></table>
 * 
 */
public class DefaultS4CreateCdsMetadataService
    implements ServiceWithNavigableEntities, S4CreateCdsMetadataService
{

    @Nonnull
    @Getter
    private final String servicePath;

    /**
     * Creates a service using {@link S4CreateCdsMetadataService#DEFAULT_SERVICE_PATH} to send the requests.
     * 
     */
    public DefaultS4CreateCdsMetadataService() {
        servicePath = S4CreateCdsMetadataService.DEFAULT_SERVICE_PATH;
    }

    /**
     * Creates a service using the provided service path to send the requests.
     * <p>
     * Used by the fluent {@link #withServicePath(String)} method.
     * 
     */
    private DefaultS4CreateCdsMetadataService(
        @Nonnull
        final String servicePath) {
        this.servicePath = servicePath;
    }

    @Override
    @Nonnull
    public DefaultS4CreateCdsMetadataService withServicePath(
        @Nonnull
        final String servicePath) {
        return new DefaultS4CreateCdsMetadataService(servicePath);
    }

    @Override
    @Nonnull
    public BatchRequestBuilder batch() {
        return new BatchRequestBuilder(servicePath);
    }

    @Override
    @Nonnull
    public GetAllRequestBuilder<DraftAdministrationData> getAllI_DraftAdministrativeData() {
        return new GetAllRequestBuilder<DraftAdministrationData>(servicePath, DraftAdministrationData.class, "I_DraftAdministrativeData");
    }

    @Override
    @Nonnull
    public CountRequestBuilder<DraftAdministrationData> countI_DraftAdministrativeData() {
        return new CountRequestBuilder<DraftAdministrationData>(servicePath, DraftAdministrationData.class, "I_DraftAdministrativeData");
    }

    @Override
    @Nonnull
    public GetByKeyRequestBuilder<DraftAdministrationData> getI_DraftAdministrativeDataByKey(final UUID draftTechnicalID, final String draftEntityID) {
        final Map<String, Object> key = new HashMap<String, Object>();
        key.put("DraftUUID", draftTechnicalID);
        key.put("DraftEntityType", draftEntityID);
        return new GetByKeyRequestBuilder<DraftAdministrationData>(servicePath, DraftAdministrationData.class, key, "I_DraftAdministrativeData");
    }

    @Override
    @Nonnull
    public GetAllRequestBuilder<ConsumptionViewForGenerateDdlsl> getAllZc_genddls_l() {
        return new GetAllRequestBuilder<ConsumptionViewForGenerateDdlsl>(servicePath, ConsumptionViewForGenerateDdlsl.class, "zc_genddls_l");
    }

    @Override
    @Nonnull
    public CountRequestBuilder<ConsumptionViewForGenerateDdlsl> countZc_genddls_l() {
        return new CountRequestBuilder<ConsumptionViewForGenerateDdlsl>(servicePath, ConsumptionViewForGenerateDdlsl.class, "zc_genddls_l");
    }

    @Override
    @Nonnull
    public GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlsl> getZc_genddls_lByKey(final String projectName, final UUID uUID, final Boolean isActive) {
        final Map<String, Object> key = new HashMap<String, Object>();
        key.put("Projname", projectName);
        key.put("UUID", uUID);
        key.put("IsActiveEntity", isActive);
        return new GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlsl>(servicePath, ConsumptionViewForGenerateDdlsl.class, key, "zc_genddls_l");
    }

    @Override
    @Nonnull
    public UpdateRequestBuilder<ConsumptionViewForGenerateDdlsl> updateZc_genddls_l(
        @Nonnull
        final ConsumptionViewForGenerateDdlsl consumptionViewForGenerateDdlsl) {
        return new UpdateRequestBuilder<ConsumptionViewForGenerateDdlsl>(servicePath, consumptionViewForGenerateDdlsl, "zc_genddls_l");
    }

    @Override
    @Nonnull
    public DeleteRequestBuilder<ConsumptionViewForGenerateDdlsl> deleteZc_genddls_l(
        @Nonnull
        final ConsumptionViewForGenerateDdlsl consumptionViewForGenerateDdlsl) {
        return new DeleteRequestBuilder<ConsumptionViewForGenerateDdlsl>(servicePath, consumptionViewForGenerateDdlsl, "zc_genddls_l");
    }

    @Override
    @Nonnull
    public GetAllRequestBuilder<ConsumptionViewForGenerateDdlsp> getAllZc_genddls_p() {
        return new GetAllRequestBuilder<ConsumptionViewForGenerateDdlsp>(servicePath, ConsumptionViewForGenerateDdlsp.class, "zc_genddls_p");
    }

    @Override
    @Nonnull
    public CountRequestBuilder<ConsumptionViewForGenerateDdlsp> countZc_genddls_p() {
        return new CountRequestBuilder<ConsumptionViewForGenerateDdlsp>(servicePath, ConsumptionViewForGenerateDdlsp.class, "zc_genddls_p");
    }

    @Override
    @Nonnull
    public GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlsp> getZc_genddls_pByKey(final String projectName, final Boolean isActive) {
        final Map<String, Object> key = new HashMap<String, Object>();
        key.put("Projname", projectName);
        key.put("IsActiveEntity", isActive);
        return new GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlsp>(servicePath, ConsumptionViewForGenerateDdlsp.class, key, "zc_genddls_p");
    }

    @Override
    @Nonnull
    public CreateRequestBuilder<ConsumptionViewForGenerateDdlsp> createZc_genddls_p(
        @Nonnull
        final ConsumptionViewForGenerateDdlsp consumptionViewForGenerateDdlsp) {
        return new CreateRequestBuilder<ConsumptionViewForGenerateDdlsp>(servicePath, consumptionViewForGenerateDdlsp, "zc_genddls_p");
    }

    @Override
    @Nonnull
    public UpdateRequestBuilder<ConsumptionViewForGenerateDdlsp> updateZc_genddls_p(
        @Nonnull
        final ConsumptionViewForGenerateDdlsp consumptionViewForGenerateDdlsp) {
        return new UpdateRequestBuilder<ConsumptionViewForGenerateDdlsp>(servicePath, consumptionViewForGenerateDdlsp, "zc_genddls_p");
    }

    @Override
    @Nonnull
    public DeleteRequestBuilder<ConsumptionViewForGenerateDdlsp> deleteZc_genddls_p(
        @Nonnull
        final ConsumptionViewForGenerateDdlsp consumptionViewForGenerateDdlsp) {
        return new DeleteRequestBuilder<ConsumptionViewForGenerateDdlsp>(servicePath, consumptionViewForGenerateDdlsp, "zc_genddls_p");
    }

    @Override
    @Nonnull
    public GetAllRequestBuilder<ConsumptionViewForGenerateDdlss> getAllZc_genddls_s() {
        return new GetAllRequestBuilder<ConsumptionViewForGenerateDdlss>(servicePath, ConsumptionViewForGenerateDdlss.class, "zc_genddls_s");
    }

    @Override
    @Nonnull
    public CountRequestBuilder<ConsumptionViewForGenerateDdlss> countZc_genddls_s() {
        return new CountRequestBuilder<ConsumptionViewForGenerateDdlss>(servicePath, ConsumptionViewForGenerateDdlss.class, "zc_genddls_s");
    }

    @Override
    @Nonnull
    public GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlss> getZc_genddls_sByKey(final String projectName, final String viewName, final Boolean isActive) {
        final Map<String, Object> key = new HashMap<String, Object>();
        key.put("Projname", projectName);
        key.put("Viewname", viewName);
        key.put("IsActiveEntity", isActive);
        return new GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlss>(servicePath, ConsumptionViewForGenerateDdlss.class, key, "zc_genddls_s");
    }

    @Override
    @Nonnull
    public UpdateRequestBuilder<ConsumptionViewForGenerateDdlss> updateZc_genddls_s(
        @Nonnull
        final ConsumptionViewForGenerateDdlss consumptionViewForGenerateDdlss) {
        return new UpdateRequestBuilder<ConsumptionViewForGenerateDdlss>(servicePath, consumptionViewForGenerateDdlss, "zc_genddls_s");
    }

    @Override
    @Nonnull
    public DeleteRequestBuilder<ConsumptionViewForGenerateDdlss> deleteZc_genddls_s(
        @Nonnull
        final ConsumptionViewForGenerateDdlss consumptionViewForGenerateDdlss) {
        return new DeleteRequestBuilder<ConsumptionViewForGenerateDdlss>(servicePath, consumptionViewForGenerateDdlss, "zc_genddls_s");
    }

}
