
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.services;

import java.util.UUID;
import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss;
import customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>s4_create_cds_metadata</td></tr></table>
 * 
 */
public interface S4CreateCdsMetadataService {

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "odata/v4/com.sap.gateway.srvd.zsrvd_genddls.v0001";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    S4CreateCdsMetadataService withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Creates a batch request builder object.
     * 
     * @return
     *     A request builder to handle batch operation on this service. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder#execute(Destination) execute} method on the request builder object.
     */
    @Nonnull
    BatchRequestBuilder batch();

    /**
     * Fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData DraftAdministrationData} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData DraftAdministrationData} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<DraftAdministrationData> getAllI_DraftAdministrativeData();

    /**
     * Fetch the number of entries from the {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData DraftAdministrationData} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData DraftAdministrationData} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<DraftAdministrationData> countI_DraftAdministrativeData();

    /**
     * Fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData DraftAdministrationData} entity using key fields.
     * 
     * @param draftEntityID
     *     Draft Entity ID<p>Constraints: Not nullable, Maximum length: 30</p>
     * @param draftTechnicalID
     *     Draft (Technical ID)<p>Constraints: Not nullable</p>
     * @return
     *     A request builder to fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData DraftAdministrationData} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.DraftAdministrationData>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<DraftAdministrationData> getI_DraftAdministrativeDataByKey(final UUID draftTechnicalID, final String draftEntityID);

    /**
     * Fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<ConsumptionViewForGenerateDdlsl> getAllZc_genddls_l();

    /**
     * Fetch the number of entries from the {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<ConsumptionViewForGenerateDdlsl> countZc_genddls_l();

    /**
     * Fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity using key fields.
     * 
     * @param projectName
     *     Project name<p>Constraints: Not nullable, Maximum length: 30</p>
     * @param isActive
     *     Draft - Indicator - Is active document<p>Constraints: Not nullable</p>
     * @param uUID
     *      16 Byte UUID in 16 Bytes (Raw Format)<p>Constraints: Not nullable</p>
     * @return
     *     A request builder to fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlsl> getZc_genddls_lByKey(final String projectName, final UUID uUID, final Boolean isActive);

    /**
     * Update an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity and save it to the S/4HANA system.
     * 
     * @param consumptionViewForGenerateDdlsl
     *     {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity object that will be updated in the S/4HANA system.
     * @return
     *     A request builder to update an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl>#execute execute} method on the request builder object. 
     */
    @Nonnull
    UpdateRequestBuilder<ConsumptionViewForGenerateDdlsl> updateZc_genddls_l(
        @Nonnull
        final ConsumptionViewForGenerateDdlsl consumptionViewForGenerateDdlsl);

    /**
     * Deletes an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity in the S/4HANA system.
     * 
     * @param consumptionViewForGenerateDdlsl
     *     {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A request builder to delete an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl ConsumptionViewForGenerateDdlsl} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsl>#execute execute} method on the request builder object. 
     */
    @Nonnull
    DeleteRequestBuilder<ConsumptionViewForGenerateDdlsl> deleteZc_genddls_l(
        @Nonnull
        final ConsumptionViewForGenerateDdlsl consumptionViewForGenerateDdlsl);

    /**
     * Fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<ConsumptionViewForGenerateDdlsp> getAllZc_genddls_p();

    /**
     * Fetch the number of entries from the {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<ConsumptionViewForGenerateDdlsp> countZc_genddls_p();

    /**
     * Fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity using key fields.
     * 
     * @param projectName
     *     Project name<p>Constraints: Not nullable, Maximum length: 30</p>
     * @param isActive
     *     Draft - Indicator - Is active document<p>Constraints: Not nullable</p>
     * @return
     *     A request builder to fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlsp> getZc_genddls_pByKey(final String projectName, final Boolean isActive);

    /**
     * Create a new {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity and save it to the S/4HANA system.
     * 
     * @param consumptionViewForGenerateDdlsp
     *     {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity object that will be created in the S/4HANA system.
     * @return
     *     A request builder to create a new {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CreateRequestBuilder<ConsumptionViewForGenerateDdlsp> createZc_genddls_p(
        @Nonnull
        final ConsumptionViewForGenerateDdlsp consumptionViewForGenerateDdlsp);

    /**
     * Update an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity and save it to the S/4HANA system.
     * 
     * @param consumptionViewForGenerateDdlsp
     *     {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity object that will be updated in the S/4HANA system.
     * @return
     *     A request builder to update an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp>#execute execute} method on the request builder object. 
     */
    @Nonnull
    UpdateRequestBuilder<ConsumptionViewForGenerateDdlsp> updateZc_genddls_p(
        @Nonnull
        final ConsumptionViewForGenerateDdlsp consumptionViewForGenerateDdlsp);

    /**
     * Deletes an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity in the S/4HANA system.
     * 
     * @param consumptionViewForGenerateDdlsp
     *     {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A request builder to delete an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp ConsumptionViewForGenerateDdlsp} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlsp>#execute execute} method on the request builder object. 
     */
    @Nonnull
    DeleteRequestBuilder<ConsumptionViewForGenerateDdlsp> deleteZc_genddls_p(
        @Nonnull
        final ConsumptionViewForGenerateDdlsp consumptionViewForGenerateDdlsp);

    /**
     * Fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<ConsumptionViewForGenerateDdlss> getAllZc_genddls_s();

    /**
     * Fetch the number of entries from the {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<ConsumptionViewForGenerateDdlss> countZc_genddls_s();

    /**
     * Fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity using key fields.
     * 
     * @param viewName
     *     View name<p>Constraints: Not nullable, Maximum length: 40</p>
     * @param projectName
     *     Project name<p>Constraints: Not nullable, Maximum length: 30</p>
     * @param isActive
     *     Draft - Indicator - Is active document<p>Constraints: Not nullable</p>
     * @return
     *     A request builder to fetch a single {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<ConsumptionViewForGenerateDdlss> getZc_genddls_sByKey(final String projectName, final String viewName, final Boolean isActive);

    /**
     * Update an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity and save it to the S/4HANA system.
     * 
     * @param consumptionViewForGenerateDdlss
     *     {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity object that will be updated in the S/4HANA system.
     * @return
     *     A request builder to update an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss>#execute execute} method on the request builder object. 
     */
    @Nonnull
    UpdateRequestBuilder<ConsumptionViewForGenerateDdlss> updateZc_genddls_s(
        @Nonnull
        final ConsumptionViewForGenerateDdlss consumptionViewForGenerateDdlss);

    /**
     * Deletes an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity in the S/4HANA system.
     * 
     * @param consumptionViewForGenerateDdlss
     *     {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A request builder to delete an existing {@link customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss ConsumptionViewForGenerateDdlss} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder<customer.ai2code.model.s4.namespaces.s4createcdsmetadata.ConsumptionViewForGenerateDdlss>#execute execute} method on the request builder object. 
     */
    @Nonnull
    DeleteRequestBuilder<ConsumptionViewForGenerateDdlss> deleteZc_genddls_s(
        @Nonnull
        final ConsumptionViewForGenerateDdlss consumptionViewForGenerateDdlss);

}
