
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.time.OffsetDateTime;
import java.util.LinkedList;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import customer.ai2code.model.s4.services.S4CreateCdsMetadataService;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


/**
 * Consumption view for generate ddls -s<p></p><p>Original entity name from the Odata EDM: <b>zc_genddls_sType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class ConsumptionViewForGenerateDdlss
    extends VdmEntity<ConsumptionViewForGenerateDdlss>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.zc_genddls_sType";
    /**
     * Selector for all available fields of ConsumptionViewForGenerateDdlss.
     * 
     */
    public final static SimpleProperty<ConsumptionViewForGenerateDdlss> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Projname</b></p>
     * 
     * @return
     *     Project name
     */
    @Nullable
    @ElementName("Projname")
    private java.lang.String projectName;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlss> PROJECT_NAME = new SimpleProperty.String<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "Projname");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Viewname</b></p>
     * 
     * @return
     *     View name
     */
    @Nullable
    @ElementName("Viewname")
    private java.lang.String viewName;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlss> VIEW_NAME = new SimpleProperty.String<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "Viewname");
    /**
     * Constraints: Not nullable, Maximum length: 60 <p>Original property name from the Odata EDM: <b>Viewdesc</b></p>
     * 
     * @return
     *     View description
     */
    @Nullable
    @ElementName("Viewdesc")
    private java.lang.String viewDescription;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlss> VIEW_DESCRIPTION = new SimpleProperty.String<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "Viewdesc");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Reference</b></p>
     * 
     * @return
     *     Reference
     */
    @Nullable
    @ElementName("Reference")
    private java.lang.String reference;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlss> REFERENCE = new SimpleProperty.String<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "Reference");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Sourcecode</b></p>
     * 
     * @return
     *     CDS Source code
     */
    @Nullable
    @ElementName("Sourcecode")
    private java.lang.String cDSSourceCode;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlss> CDS_SOURCE_CODE = new SimpleProperty.String<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "Sourcecode");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedBy</b></p>
     * 
     * @return
     *     Created By User
     */
    @Nullable
    @ElementName("CreatedBy")
    private java.lang.String createdBy;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlss> CREATED_BY = new SimpleProperty.String<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "CreatedBy");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreatedAt</b></p>
     * 
     * @return
     *     Creation Date Time
     */
    @Nullable
    @ElementName("CreatedAt")
    private OffsetDateTime createdOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss> CREATED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "CreatedAt");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LocalLastChangedBy</b></p>
     * 
     * @return
     *     Local Instance Last Changed By User
     */
    @Nullable
    @ElementName("LocalLastChangedBy")
    private java.lang.String changedBy;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlss> CHANGED_BY = new SimpleProperty.String<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "LocalLastChangedBy");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LocalLastChangedAt</b></p>
     * 
     * @return
     *     Local Instance Last Change Date Time
     */
    @Nullable
    @ElementName("LocalLastChangedAt")
    private OffsetDateTime changedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss> CHANGED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "LocalLastChangedAt");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasDraftEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Has draft document
     */
    @Nullable
    @ElementName("HasDraftEntity")
    private java.lang.Boolean hasDraft;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlss> HAS_DRAFT = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "HasDraftEntity");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityCreationDateTime</b></p>
     * 
     * @return
     *     Draft Created On
     */
    @Nullable
    @ElementName("DraftEntityCreationDateTime")
    private OffsetDateTime draftCreatedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss> DRAFT_CREATED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "DraftEntityCreationDateTime");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityLastChangeDateTime</b></p>
     * 
     * @return
     *     Draft Last Changed On
     */
    @Nullable
    @ElementName("DraftEntityLastChangeDateTime")
    private OffsetDateTime draftLastChangedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss> DRAFT_LAST_CHANGED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "DraftEntityLastChangeDateTime");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasActiveEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Has active document
     */
    @Nullable
    @ElementName("HasActiveEntity")
    private java.lang.Boolean hasActive;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlss> HAS_ACTIVE = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "HasActiveEntity");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>IsActiveEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Is active document
     */
    @Nullable
    @ElementName("IsActiveEntity")
    private java.lang.Boolean isActive;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlss> IS_ACTIVE = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "IsActiveEntity");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__EntityControl</b></p>
     * 
     * @return
     *     The __EntityControl contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("__EntityControl")
    private EntityControl __EntityControl;
    /**
     * Use with available request builders to apply the <b>__EntityControl</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlss, EntityControl> _ENTITY_CONTROL = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlss, EntityControl>(ConsumptionViewForGenerateDdlss.class, "__EntityControl", EntityControl.class);
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SAP__Messages</b></p>
     * 
     * @return
     *     The _Messages contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("SAP__Messages")
    private java.util.Collection<SAP__Message> _Messages;
    /**
     * Use with available request builders to apply the <b>SAP__Messages</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<ConsumptionViewForGenerateDdlss, SAP__Message> _MESSAGES = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<ConsumptionViewForGenerateDdlss, SAP__Message>(ConsumptionViewForGenerateDdlss.class, "SAP__Messages", SAP__Message.class);
    /**
     * Navigation property <b>DraftAdministrativeData</b> for <b>ConsumptionViewForGenerateDdlss</b> to single <b>DraftAdministrationData</b>.
     * 
     */
    @ElementName("DraftAdministrativeData")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private DraftAdministrationData toDraftAdministrativeData;
    /**
     * Navigation property <b>SiblingEntity</b> for <b>ConsumptionViewForGenerateDdlss</b> to single <b>ConsumptionViewForGenerateDdlss</b>.
     * 
     */
    @ElementName("SiblingEntity")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private ConsumptionViewForGenerateDdlss toSiblingEntity;
    /**
     * Navigation property <b>_proj</b> for <b>ConsumptionViewForGenerateDdlss</b> to single <b>ConsumptionViewForGenerateDdlsp</b>.
     * 
     */
    @ElementName("_proj")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private ConsumptionViewForGenerateDdlsp to_proj;
    /**
     * Use with available request builders to apply the <b>DraftAdministrativeData</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlss, DraftAdministrationData> TO_DRAFT_ADMINISTRATIVE_DATA = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlss, DraftAdministrationData>(ConsumptionViewForGenerateDdlss.class, "DraftAdministrativeData", DraftAdministrationData.class);
    /**
     * Use with available request builders to apply the <b>SiblingEntity</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlss, ConsumptionViewForGenerateDdlss> TO_SIBLING_ENTITY = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlss, ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlss.class, "SiblingEntity", ConsumptionViewForGenerateDdlss.class);
    /**
     * Use with available request builders to apply the <b>_proj</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlss, ConsumptionViewForGenerateDdlsp> TO__PROJ = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlss, ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlss.class, "_proj", ConsumptionViewForGenerateDdlsp.class);

    @Nonnull
    @Override
    public Class<ConsumptionViewForGenerateDdlss> getType() {
        return ConsumptionViewForGenerateDdlss.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Projname</b></p>
     * 
     * @param projectName
     *     Project name
     */
    public void setProjectName(
        @Nullable
        final java.lang.String projectName) {
        rememberChangedField("Projname", this.projectName);
        this.projectName = projectName;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Viewname</b></p>
     * 
     * @param viewName
     *     View name
     */
    public void setViewName(
        @Nullable
        final java.lang.String viewName) {
        rememberChangedField("Viewname", this.viewName);
        this.viewName = viewName;
    }

    /**
     * Constraints: Not nullable, Maximum length: 60 <p>Original property name from the Odata EDM: <b>Viewdesc</b></p>
     * 
     * @param viewDescription
     *     View description
     */
    public void setViewDescription(
        @Nullable
        final java.lang.String viewDescription) {
        rememberChangedField("Viewdesc", this.viewDescription);
        this.viewDescription = viewDescription;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Reference</b></p>
     * 
     * @param reference
     *     Reference
     */
    public void setReference(
        @Nullable
        final java.lang.String reference) {
        rememberChangedField("Reference", this.reference);
        this.reference = reference;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Sourcecode</b></p>
     * 
     * @param cDSSourceCode
     *     CDS Source code
     */
    public void setCDSSourceCode(
        @Nullable
        final java.lang.String cDSSourceCode) {
        rememberChangedField("Sourcecode", this.cDSSourceCode);
        this.cDSSourceCode = cDSSourceCode;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedBy</b></p>
     * 
     * @param createdBy
     *     Created By User
     */
    public void setCreatedBy(
        @Nullable
        final java.lang.String createdBy) {
        rememberChangedField("CreatedBy", this.createdBy);
        this.createdBy = createdBy;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreatedAt</b></p>
     * 
     * @param createdOn
     *     Creation Date Time
     */
    public void setCreatedOn(
        @Nullable
        final OffsetDateTime createdOn) {
        rememberChangedField("CreatedAt", this.createdOn);
        this.createdOn = createdOn;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LocalLastChangedBy</b></p>
     * 
     * @param changedBy
     *     Local Instance Last Changed By User
     */
    public void setChangedBy(
        @Nullable
        final java.lang.String changedBy) {
        rememberChangedField("LocalLastChangedBy", this.changedBy);
        this.changedBy = changedBy;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LocalLastChangedAt</b></p>
     * 
     * @param changedOn
     *     Local Instance Last Change Date Time
     */
    public void setChangedOn(
        @Nullable
        final OffsetDateTime changedOn) {
        rememberChangedField("LocalLastChangedAt", this.changedOn);
        this.changedOn = changedOn;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasDraftEntity</b></p>
     * 
     * @param hasDraft
     *     Draft - Indicator - Has draft document
     */
    public void setHasDraft(
        @Nullable
        final java.lang.Boolean hasDraft) {
        rememberChangedField("HasDraftEntity", this.hasDraft);
        this.hasDraft = hasDraft;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityCreationDateTime</b></p>
     * 
     * @param draftCreatedOn
     *     Draft Created On
     */
    public void setDraftCreatedOn(
        @Nullable
        final OffsetDateTime draftCreatedOn) {
        rememberChangedField("DraftEntityCreationDateTime", this.draftCreatedOn);
        this.draftCreatedOn = draftCreatedOn;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityLastChangeDateTime</b></p>
     * 
     * @param draftLastChangedOn
     *     Draft Last Changed On
     */
    public void setDraftLastChangedOn(
        @Nullable
        final OffsetDateTime draftLastChangedOn) {
        rememberChangedField("DraftEntityLastChangeDateTime", this.draftLastChangedOn);
        this.draftLastChangedOn = draftLastChangedOn;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasActiveEntity</b></p>
     * 
     * @param hasActive
     *     Draft - Indicator - Has active document
     */
    public void setHasActive(
        @Nullable
        final java.lang.Boolean hasActive) {
        rememberChangedField("HasActiveEntity", this.hasActive);
        this.hasActive = hasActive;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>IsActiveEntity</b></p>
     * 
     * @param isActive
     *     Draft - Indicator - Is active document
     */
    public void setIsActive(
        @Nullable
        final java.lang.Boolean isActive) {
        rememberChangedField("IsActiveEntity", this.isActive);
        this.isActive = isActive;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__EntityControl</b></p>
     * 
     * @param __EntityControl
     *     The __EntityControl to set.
     */
    public void set__EntityControl(
        @Nullable
        final EntityControl __EntityControl) {
        rememberChangedField("__EntityControl", this.__EntityControl);
        this.__EntityControl = __EntityControl;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SAP__Messages</b></p>
     * 
     * @param _Messages
     *     The _Messages to set.
     */
    public void set_Messages(
        @Nullable
        final java.util.Collection<SAP__Message> _Messages) {
        rememberChangedField("SAP__Messages", this._Messages);
        this._Messages = _Messages;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "zc_genddls_s";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("Projname", getProjectName());
        entityKey.addKeyProperty("Viewname", getViewName());
        entityKey.addKeyProperty("IsActiveEntity", getIsActive());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("Projname", getProjectName());
        cloudSdkValues.put("Viewname", getViewName());
        cloudSdkValues.put("Viewdesc", getViewDescription());
        cloudSdkValues.put("Reference", getReference());
        cloudSdkValues.put("Sourcecode", getCDSSourceCode());
        cloudSdkValues.put("CreatedBy", getCreatedBy());
        cloudSdkValues.put("CreatedAt", getCreatedOn());
        cloudSdkValues.put("LocalLastChangedBy", getChangedBy());
        cloudSdkValues.put("LocalLastChangedAt", getChangedOn());
        cloudSdkValues.put("HasDraftEntity", getHasDraft());
        cloudSdkValues.put("DraftEntityCreationDateTime", getDraftCreatedOn());
        cloudSdkValues.put("DraftEntityLastChangeDateTime", getDraftLastChangedOn());
        cloudSdkValues.put("HasActiveEntity", getHasActive());
        cloudSdkValues.put("IsActiveEntity", getIsActive());
        cloudSdkValues.put("__EntityControl", get__EntityControl());
        cloudSdkValues.put("SAP__Messages", get_Messages());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("Projname")) {
                final Object value = cloudSdkValues.remove("Projname");
                if ((value == null)||(!value.equals(getProjectName()))) {
                    setProjectName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Viewname")) {
                final Object value = cloudSdkValues.remove("Viewname");
                if ((value == null)||(!value.equals(getViewName()))) {
                    setViewName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Viewdesc")) {
                final Object value = cloudSdkValues.remove("Viewdesc");
                if ((value == null)||(!value.equals(getViewDescription()))) {
                    setViewDescription(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Reference")) {
                final Object value = cloudSdkValues.remove("Reference");
                if ((value == null)||(!value.equals(getReference()))) {
                    setReference(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Sourcecode")) {
                final Object value = cloudSdkValues.remove("Sourcecode");
                if ((value == null)||(!value.equals(getCDSSourceCode()))) {
                    setCDSSourceCode(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedBy")) {
                final Object value = cloudSdkValues.remove("CreatedBy");
                if ((value == null)||(!value.equals(getCreatedBy()))) {
                    setCreatedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedAt")) {
                final Object value = cloudSdkValues.remove("CreatedAt");
                if ((value == null)||(!value.equals(getCreatedOn()))) {
                    setCreatedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("LocalLastChangedBy")) {
                final Object value = cloudSdkValues.remove("LocalLastChangedBy");
                if ((value == null)||(!value.equals(getChangedBy()))) {
                    setChangedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("LocalLastChangedAt")) {
                final Object value = cloudSdkValues.remove("LocalLastChangedAt");
                if ((value == null)||(!value.equals(getChangedOn()))) {
                    setChangedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("HasDraftEntity")) {
                final Object value = cloudSdkValues.remove("HasDraftEntity");
                if ((value == null)||(!value.equals(getHasDraft()))) {
                    setHasDraft(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftEntityCreationDateTime")) {
                final Object value = cloudSdkValues.remove("DraftEntityCreationDateTime");
                if ((value == null)||(!value.equals(getDraftCreatedOn()))) {
                    setDraftCreatedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftEntityLastChangeDateTime")) {
                final Object value = cloudSdkValues.remove("DraftEntityLastChangeDateTime");
                if ((value == null)||(!value.equals(getDraftLastChangedOn()))) {
                    setDraftLastChangedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("HasActiveEntity")) {
                final Object value = cloudSdkValues.remove("HasActiveEntity");
                if ((value == null)||(!value.equals(getHasActive()))) {
                    setHasActive(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("IsActiveEntity")) {
                final Object value = cloudSdkValues.remove("IsActiveEntity");
                if ((value == null)||(!value.equals(getIsActive()))) {
                    setIsActive(((java.lang.Boolean) value));
                }
            }
        }
        // structured properties
        {
            if (cloudSdkValues.containsKey("__EntityControl")) {
                final Object value = cloudSdkValues.remove("__EntityControl");
                if (value instanceof Map) {
                    if (get__EntityControl() == null) {
                        set__EntityControl(new EntityControl());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                    get__EntityControl().fromMap(inputMap);
                }
                if ((value == null)&&(get__EntityControl()!= null)) {
                    set__EntityControl(null);
                }
            }
            if (cloudSdkValues.containsKey("SAP__Messages")) {
                final Object value = cloudSdkValues.remove("SAP__Messages");
                if (value instanceof Iterable) {
                    final LinkedList<SAP__Message> _Messages = new LinkedList<SAP__Message>();
                    for (Object properties: ((Iterable<?> ) value)) {
                        if (properties instanceof Map) {
                            final SAP__Message item = new SAP__Message();
                            @SuppressWarnings("unchecked")
                            final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                            item.fromMap(inputMap);
                            _Messages.add(item);
                        }
                    }
                    set_Messages(_Messages);
                }
                if ((value == null)&&(get_Messages()!= null)) {
                    set_Messages(null);
                }
            }
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("DraftAdministrativeData")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("DraftAdministrativeData");
                if (cloudSdkValue instanceof Map) {
                    if (toDraftAdministrativeData == null) {
                        toDraftAdministrativeData = new DraftAdministrationData();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    toDraftAdministrativeData.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("SiblingEntity")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("SiblingEntity");
                if (cloudSdkValue instanceof Map) {
                    if (toSiblingEntity == null) {
                        toSiblingEntity = new ConsumptionViewForGenerateDdlss();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    toSiblingEntity.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("_proj")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("_proj");
                if (cloudSdkValue instanceof Map) {
                    if (to_proj == null) {
                        to_proj = new ConsumptionViewForGenerateDdlsp();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    to_proj.fromMap(inputMap);
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return S4CreateCdsMetadataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toDraftAdministrativeData!= null) {
            (cloudSdkValues).put("DraftAdministrativeData", toDraftAdministrativeData);
        }
        if (toSiblingEntity!= null) {
            (cloudSdkValues).put("SiblingEntity", toSiblingEntity);
        }
        if (to_proj!= null) {
            (cloudSdkValues).put("_proj", to_proj);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>DraftAdministrationData</b> entity (one to one). This corresponds to the OData navigation property <b>DraftAdministrativeData</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlss</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>DraftAdministrativeData</b> is already loaded, the result will contain the <b>DraftAdministrationData</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<DraftAdministrationData> getDraftAdministrativeDataIfPresent() {
        return Option.of(toDraftAdministrativeData);
    }

    /**
     * Overwrites the associated <b>DraftAdministrationData</b> entity for the loaded navigation property <b>DraftAdministrativeData</b>.
     * 
     * @param cloudSdkValue
     *     New <b>DraftAdministrationData</b> entity.
     */
    public void setDraftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
        toDraftAdministrativeData = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>ConsumptionViewForGenerateDdlss</b> entity (one to one). This corresponds to the OData navigation property <b>SiblingEntity</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlss</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>SiblingEntity</b> is already loaded, the result will contain the <b>ConsumptionViewForGenerateDdlss</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<ConsumptionViewForGenerateDdlss> getSiblingEntityIfPresent() {
        return Option.of(toSiblingEntity);
    }

    /**
     * Overwrites the associated <b>ConsumptionViewForGenerateDdlss</b> entity for the loaded navigation property <b>SiblingEntity</b>.
     * 
     * @param cloudSdkValue
     *     New <b>ConsumptionViewForGenerateDdlss</b> entity.
     */
    public void setSiblingEntity(final ConsumptionViewForGenerateDdlss cloudSdkValue) {
        toSiblingEntity = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>ConsumptionViewForGenerateDdlsp</b> entity (one to one). This corresponds to the OData navigation property <b>_proj</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlss</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>_proj</b> is already loaded, the result will contain the <b>ConsumptionViewForGenerateDdlsp</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<ConsumptionViewForGenerateDdlsp> getProjIfPresent() {
        return Option.of(to_proj);
    }

    /**
     * Overwrites the associated <b>ConsumptionViewForGenerateDdlsp</b> entity for the loaded navigation property <b>_proj</b>.
     * 
     * @param cloudSdkValue
     *     New <b>ConsumptionViewForGenerateDdlsp</b> entity.
     */
    public void setProj(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
        to_proj = cloudSdkValue;
    }


    /**
     * Helper class to allow for fluent creation of ConsumptionViewForGenerateDdlss instances.
     * 
     */
    public final static class ConsumptionViewForGenerateDdlssBuilder {

        private DraftAdministrationData toDraftAdministrativeData;
        private ConsumptionViewForGenerateDdlss toSiblingEntity;
        private ConsumptionViewForGenerateDdlsp to_proj;

        private ConsumptionViewForGenerateDdlss.ConsumptionViewForGenerateDdlssBuilder toDraftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
            toDraftAdministrativeData = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>DraftAdministrativeData</b> for <b>ConsumptionViewForGenerateDdlss</b> to single <b>DraftAdministrationData</b>.
         * 
         * @param cloudSdkValue
         *     The DraftAdministrationData to build this ConsumptionViewForGenerateDdlss with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlss.ConsumptionViewForGenerateDdlssBuilder draftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
            return toDraftAdministrativeData(cloudSdkValue);
        }

        private ConsumptionViewForGenerateDdlss.ConsumptionViewForGenerateDdlssBuilder toSiblingEntity(final ConsumptionViewForGenerateDdlss cloudSdkValue) {
            toSiblingEntity = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>SiblingEntity</b> for <b>ConsumptionViewForGenerateDdlss</b> to single <b>ConsumptionViewForGenerateDdlss</b>.
         * 
         * @param cloudSdkValue
         *     The ConsumptionViewForGenerateDdlss to build this ConsumptionViewForGenerateDdlss with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlss.ConsumptionViewForGenerateDdlssBuilder siblingEntity(final ConsumptionViewForGenerateDdlss cloudSdkValue) {
            return toSiblingEntity(cloudSdkValue);
        }

        private ConsumptionViewForGenerateDdlss.ConsumptionViewForGenerateDdlssBuilder to_proj(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
            to_proj = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>_proj</b> for <b>ConsumptionViewForGenerateDdlss</b> to single <b>ConsumptionViewForGenerateDdlsp</b>.
         * 
         * @param cloudSdkValue
         *     The ConsumptionViewForGenerateDdlsp to build this ConsumptionViewForGenerateDdlss with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlss.ConsumptionViewForGenerateDdlssBuilder proj(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
            return to_proj(cloudSdkValue);
        }

    }

}
