
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.time.OffsetDateTime;
import java.util.LinkedList;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import customer.ai2code.model.s4.services.S4CreateCdsMetadataService;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


/**
 * Consumption view for generate ddls -l<p></p><p>Original entity name from the Odata EDM: <b>zc_genddls_lType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class ConsumptionViewForGenerateDdlsl
    extends VdmEntity<ConsumptionViewForGenerateDdlsl>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.zc_genddls_lType";
    /**
     * Selector for all available fields of ConsumptionViewForGenerateDdlsl.
     * 
     */
    public final static SimpleProperty<ConsumptionViewForGenerateDdlsl> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Projname</b></p>
     * 
     * @return
     *     Project name
     */
    @Nullable
    @ElementName("Projname")
    private java.lang.String projectName;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> PROJECT_NAME = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "Projname");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>UUID</b></p>
     * 
     * @return
     *      16 Byte UUID in 16 Bytes (Raw Format)
     */
    @Nullable
    @ElementName("UUID")
    private java.util.UUID uUID;
    public final static SimpleProperty.Guid<ConsumptionViewForGenerateDdlsl> UUID = new SimpleProperty.Guid<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "UUID");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Reference</b></p>
     * 
     * @return
     *     Reference
     */
    @Nullable
    @ElementName("Reference")
    private java.lang.String reference;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> REFERENCE = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "Reference");
    /**
     * Constraints: Not nullable, Maximum length: 220 <p>Original property name from the Odata EDM: <b>Message</b></p>
     * 
     * @return
     *     Message Text
     */
    @Nullable
    @ElementName("Message")
    private java.lang.String message;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> MESSAGE = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "Message");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Type</b></p>
     * 
     * @return
     *     Message type: S Success, E Error, W Warning, I Info, A Abort
     */
    @Nullable
    @ElementName("Type")
    private java.lang.String messageType;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> MESSAGE_TYPE = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "Type");
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Id</b></p>
     * 
     * @return
     *     Message Class
     */
    @Nullable
    @ElementName("Id")
    private java.lang.String messageID;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> MESSAGE_ID = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "Id");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV1</b></p>
     * 
     * @return
     *     Message Variable
     */
    @Nullable
    @ElementName("MessageV1")
    private java.lang.String messageVariable;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> MESSAGE_VARIABLE = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "MessageV1");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV2</b></p>
     * 
     * @return
     *     Message Variable
     */
    @Nullable
    @ElementName("MessageV2")
    private java.lang.String messageVariable_2;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> MESSAGE_VARIABLE_2 = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "MessageV2");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV3</b></p>
     * 
     * @return
     *     Message Variable
     */
    @Nullable
    @ElementName("MessageV3")
    private java.lang.String messageVariable_3;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> MESSAGE_VARIABLE_3 = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "MessageV3");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV4</b></p>
     * 
     * @return
     *     Message Variable
     */
    @Nullable
    @ElementName("MessageV4")
    private java.lang.String messageVariable_4;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> MESSAGE_VARIABLE_4 = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "MessageV4");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedBy</b></p>
     * 
     * @return
     *     Created By User
     */
    @Nullable
    @ElementName("CreatedBy")
    private java.lang.String createdBy;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> CREATED_BY = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "CreatedBy");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreatedAt</b></p>
     * 
     * @return
     *     Creation Date Time
     */
    @Nullable
    @ElementName("CreatedAt")
    private OffsetDateTime createdOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl> CREATED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "CreatedAt");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LocalLastChangedBy</b></p>
     * 
     * @return
     *     Local Instance Last Changed By User
     */
    @Nullable
    @ElementName("LocalLastChangedBy")
    private java.lang.String changedBy;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsl> CHANGED_BY = new SimpleProperty.String<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "LocalLastChangedBy");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LocalLastChangedAt</b></p>
     * 
     * @return
     *     Local Instance Last Change Date Time
     */
    @Nullable
    @ElementName("LocalLastChangedAt")
    private OffsetDateTime changedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl> CHANGED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "LocalLastChangedAt");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasDraftEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Has draft document
     */
    @Nullable
    @ElementName("HasDraftEntity")
    private java.lang.Boolean hasDraft;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsl> HAS_DRAFT = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "HasDraftEntity");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityCreationDateTime</b></p>
     * 
     * @return
     *     Draft Created On
     */
    @Nullable
    @ElementName("DraftEntityCreationDateTime")
    private OffsetDateTime draftCreatedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl> DRAFT_CREATED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "DraftEntityCreationDateTime");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityLastChangeDateTime</b></p>
     * 
     * @return
     *     Draft Last Changed On
     */
    @Nullable
    @ElementName("DraftEntityLastChangeDateTime")
    private OffsetDateTime draftLastChangedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl> DRAFT_LAST_CHANGED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "DraftEntityLastChangeDateTime");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasActiveEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Has active document
     */
    @Nullable
    @ElementName("HasActiveEntity")
    private java.lang.Boolean hasActive;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsl> HAS_ACTIVE = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "HasActiveEntity");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>IsActiveEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Is active document
     */
    @Nullable
    @ElementName("IsActiveEntity")
    private java.lang.Boolean isActive;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsl> IS_ACTIVE = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "IsActiveEntity");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__EntityControl</b></p>
     * 
     * @return
     *     The __EntityControl contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("__EntityControl")
    private EntityControl __EntityControl;
    /**
     * Use with available request builders to apply the <b>__EntityControl</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsl, EntityControl> _ENTITY_CONTROL = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsl, EntityControl>(ConsumptionViewForGenerateDdlsl.class, "__EntityControl", EntityControl.class);
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SAP__Messages</b></p>
     * 
     * @return
     *     The _Messages contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("SAP__Messages")
    private java.util.Collection<SAP__Message> _Messages;
    /**
     * Use with available request builders to apply the <b>SAP__Messages</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<ConsumptionViewForGenerateDdlsl, SAP__Message> _MESSAGES = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<ConsumptionViewForGenerateDdlsl, SAP__Message>(ConsumptionViewForGenerateDdlsl.class, "SAP__Messages", SAP__Message.class);
    /**
     * Navigation property <b>DraftAdministrativeData</b> for <b>ConsumptionViewForGenerateDdlsl</b> to single <b>DraftAdministrationData</b>.
     * 
     */
    @ElementName("DraftAdministrativeData")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private DraftAdministrationData toDraftAdministrativeData;
    /**
     * Navigation property <b>SiblingEntity</b> for <b>ConsumptionViewForGenerateDdlsl</b> to single <b>ConsumptionViewForGenerateDdlsl</b>.
     * 
     */
    @ElementName("SiblingEntity")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private ConsumptionViewForGenerateDdlsl toSiblingEntity;
    /**
     * Navigation property <b>_proj</b> for <b>ConsumptionViewForGenerateDdlsl</b> to single <b>ConsumptionViewForGenerateDdlsp</b>.
     * 
     */
    @ElementName("_proj")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private ConsumptionViewForGenerateDdlsp to_proj;
    /**
     * Use with available request builders to apply the <b>DraftAdministrativeData</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsl, DraftAdministrationData> TO_DRAFT_ADMINISTRATIVE_DATA = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsl, DraftAdministrationData>(ConsumptionViewForGenerateDdlsl.class, "DraftAdministrativeData", DraftAdministrationData.class);
    /**
     * Use with available request builders to apply the <b>SiblingEntity</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsl, ConsumptionViewForGenerateDdlsl> TO_SIBLING_ENTITY = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsl, ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsl.class, "SiblingEntity", ConsumptionViewForGenerateDdlsl.class);
    /**
     * Use with available request builders to apply the <b>_proj</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsl, ConsumptionViewForGenerateDdlsp> TO__PROJ = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsl, ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsl.class, "_proj", ConsumptionViewForGenerateDdlsp.class);

    @Nonnull
    @Override
    public Class<ConsumptionViewForGenerateDdlsl> getType() {
        return ConsumptionViewForGenerateDdlsl.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Projname</b></p>
     * 
     * @param projectName
     *     Project name
     */
    public void setProjectName(
        @Nullable
        final java.lang.String projectName) {
        rememberChangedField("Projname", this.projectName);
        this.projectName = projectName;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>UUID</b></p>
     * 
     * @param uUID
     *      16 Byte UUID in 16 Bytes (Raw Format)
     */
    public void setUUID(
        @Nullable
        final java.util.UUID uUID) {
        rememberChangedField("UUID", this.uUID);
        this.uUID = uUID;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Reference</b></p>
     * 
     * @param reference
     *     Reference
     */
    public void setReference(
        @Nullable
        final java.lang.String reference) {
        rememberChangedField("Reference", this.reference);
        this.reference = reference;
    }

    /**
     * Constraints: Not nullable, Maximum length: 220 <p>Original property name from the Odata EDM: <b>Message</b></p>
     * 
     * @param message
     *     Message Text
     */
    public void setMessage(
        @Nullable
        final java.lang.String message) {
        rememberChangedField("Message", this.message);
        this.message = message;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Type</b></p>
     * 
     * @param messageType
     *     Message type: S Success, E Error, W Warning, I Info, A Abort
     */
    public void setMessageType(
        @Nullable
        final java.lang.String messageType) {
        rememberChangedField("Type", this.messageType);
        this.messageType = messageType;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Id</b></p>
     * 
     * @param messageID
     *     Message Class
     */
    public void setMessageID(
        @Nullable
        final java.lang.String messageID) {
        rememberChangedField("Id", this.messageID);
        this.messageID = messageID;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV1</b></p>
     * 
     * @param messageVariable
     *     Message Variable
     */
    public void setMessageVariable(
        @Nullable
        final java.lang.String messageVariable) {
        rememberChangedField("MessageV1", this.messageVariable);
        this.messageVariable = messageVariable;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV2</b></p>
     * 
     * @param messageVariable_2
     *     Message Variable
     */
    public void setMessageVariable_2(
        @Nullable
        final java.lang.String messageVariable_2) {
        rememberChangedField("MessageV2", this.messageVariable_2);
        this.messageVariable_2 = messageVariable_2;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV3</b></p>
     * 
     * @param messageVariable_3
     *     Message Variable
     */
    public void setMessageVariable_3(
        @Nullable
        final java.lang.String messageVariable_3) {
        rememberChangedField("MessageV3", this.messageVariable_3);
        this.messageVariable_3 = messageVariable_3;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MessageV4</b></p>
     * 
     * @param messageVariable_4
     *     Message Variable
     */
    public void setMessageVariable_4(
        @Nullable
        final java.lang.String messageVariable_4) {
        rememberChangedField("MessageV4", this.messageVariable_4);
        this.messageVariable_4 = messageVariable_4;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedBy</b></p>
     * 
     * @param createdBy
     *     Created By User
     */
    public void setCreatedBy(
        @Nullable
        final java.lang.String createdBy) {
        rememberChangedField("CreatedBy", this.createdBy);
        this.createdBy = createdBy;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreatedAt</b></p>
     * 
     * @param createdOn
     *     Creation Date Time
     */
    public void setCreatedOn(
        @Nullable
        final OffsetDateTime createdOn) {
        rememberChangedField("CreatedAt", this.createdOn);
        this.createdOn = createdOn;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LocalLastChangedBy</b></p>
     * 
     * @param changedBy
     *     Local Instance Last Changed By User
     */
    public void setChangedBy(
        @Nullable
        final java.lang.String changedBy) {
        rememberChangedField("LocalLastChangedBy", this.changedBy);
        this.changedBy = changedBy;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LocalLastChangedAt</b></p>
     * 
     * @param changedOn
     *     Local Instance Last Change Date Time
     */
    public void setChangedOn(
        @Nullable
        final OffsetDateTime changedOn) {
        rememberChangedField("LocalLastChangedAt", this.changedOn);
        this.changedOn = changedOn;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasDraftEntity</b></p>
     * 
     * @param hasDraft
     *     Draft - Indicator - Has draft document
     */
    public void setHasDraft(
        @Nullable
        final java.lang.Boolean hasDraft) {
        rememberChangedField("HasDraftEntity", this.hasDraft);
        this.hasDraft = hasDraft;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityCreationDateTime</b></p>
     * 
     * @param draftCreatedOn
     *     Draft Created On
     */
    public void setDraftCreatedOn(
        @Nullable
        final OffsetDateTime draftCreatedOn) {
        rememberChangedField("DraftEntityCreationDateTime", this.draftCreatedOn);
        this.draftCreatedOn = draftCreatedOn;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityLastChangeDateTime</b></p>
     * 
     * @param draftLastChangedOn
     *     Draft Last Changed On
     */
    public void setDraftLastChangedOn(
        @Nullable
        final OffsetDateTime draftLastChangedOn) {
        rememberChangedField("DraftEntityLastChangeDateTime", this.draftLastChangedOn);
        this.draftLastChangedOn = draftLastChangedOn;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasActiveEntity</b></p>
     * 
     * @param hasActive
     *     Draft - Indicator - Has active document
     */
    public void setHasActive(
        @Nullable
        final java.lang.Boolean hasActive) {
        rememberChangedField("HasActiveEntity", this.hasActive);
        this.hasActive = hasActive;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>IsActiveEntity</b></p>
     * 
     * @param isActive
     *     Draft - Indicator - Is active document
     */
    public void setIsActive(
        @Nullable
        final java.lang.Boolean isActive) {
        rememberChangedField("IsActiveEntity", this.isActive);
        this.isActive = isActive;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__EntityControl</b></p>
     * 
     * @param __EntityControl
     *     The __EntityControl to set.
     */
    public void set__EntityControl(
        @Nullable
        final EntityControl __EntityControl) {
        rememberChangedField("__EntityControl", this.__EntityControl);
        this.__EntityControl = __EntityControl;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SAP__Messages</b></p>
     * 
     * @param _Messages
     *     The _Messages to set.
     */
    public void set_Messages(
        @Nullable
        final java.util.Collection<SAP__Message> _Messages) {
        rememberChangedField("SAP__Messages", this._Messages);
        this._Messages = _Messages;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "zc_genddls_l";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("Projname", getProjectName());
        entityKey.addKeyProperty("UUID", getUUID());
        entityKey.addKeyProperty("IsActiveEntity", getIsActive());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("Projname", getProjectName());
        cloudSdkValues.put("UUID", getUUID());
        cloudSdkValues.put("Reference", getReference());
        cloudSdkValues.put("Message", getMessage());
        cloudSdkValues.put("Type", getMessageType());
        cloudSdkValues.put("Id", getMessageID());
        cloudSdkValues.put("MessageV1", getMessageVariable());
        cloudSdkValues.put("MessageV2", getMessageVariable_2());
        cloudSdkValues.put("MessageV3", getMessageVariable_3());
        cloudSdkValues.put("MessageV4", getMessageVariable_4());
        cloudSdkValues.put("CreatedBy", getCreatedBy());
        cloudSdkValues.put("CreatedAt", getCreatedOn());
        cloudSdkValues.put("LocalLastChangedBy", getChangedBy());
        cloudSdkValues.put("LocalLastChangedAt", getChangedOn());
        cloudSdkValues.put("HasDraftEntity", getHasDraft());
        cloudSdkValues.put("DraftEntityCreationDateTime", getDraftCreatedOn());
        cloudSdkValues.put("DraftEntityLastChangeDateTime", getDraftLastChangedOn());
        cloudSdkValues.put("HasActiveEntity", getHasActive());
        cloudSdkValues.put("IsActiveEntity", getIsActive());
        cloudSdkValues.put("__EntityControl", get__EntityControl());
        cloudSdkValues.put("SAP__Messages", get_Messages());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("Projname")) {
                final Object value = cloudSdkValues.remove("Projname");
                if ((value == null)||(!value.equals(getProjectName()))) {
                    setProjectName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("UUID")) {
                final Object value = cloudSdkValues.remove("UUID");
                if ((value == null)||(!value.equals(getUUID()))) {
                    setUUID(((java.util.UUID) value));
                }
            }
            if (cloudSdkValues.containsKey("Reference")) {
                final Object value = cloudSdkValues.remove("Reference");
                if ((value == null)||(!value.equals(getReference()))) {
                    setReference(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Message")) {
                final Object value = cloudSdkValues.remove("Message");
                if ((value == null)||(!value.equals(getMessage()))) {
                    setMessage(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Type")) {
                final Object value = cloudSdkValues.remove("Type");
                if ((value == null)||(!value.equals(getMessageType()))) {
                    setMessageType(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Id")) {
                final Object value = cloudSdkValues.remove("Id");
                if ((value == null)||(!value.equals(getMessageID()))) {
                    setMessageID(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MessageV1")) {
                final Object value = cloudSdkValues.remove("MessageV1");
                if ((value == null)||(!value.equals(getMessageVariable()))) {
                    setMessageVariable(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MessageV2")) {
                final Object value = cloudSdkValues.remove("MessageV2");
                if ((value == null)||(!value.equals(getMessageVariable_2()))) {
                    setMessageVariable_2(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MessageV3")) {
                final Object value = cloudSdkValues.remove("MessageV3");
                if ((value == null)||(!value.equals(getMessageVariable_3()))) {
                    setMessageVariable_3(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MessageV4")) {
                final Object value = cloudSdkValues.remove("MessageV4");
                if ((value == null)||(!value.equals(getMessageVariable_4()))) {
                    setMessageVariable_4(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedBy")) {
                final Object value = cloudSdkValues.remove("CreatedBy");
                if ((value == null)||(!value.equals(getCreatedBy()))) {
                    setCreatedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedAt")) {
                final Object value = cloudSdkValues.remove("CreatedAt");
                if ((value == null)||(!value.equals(getCreatedOn()))) {
                    setCreatedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("LocalLastChangedBy")) {
                final Object value = cloudSdkValues.remove("LocalLastChangedBy");
                if ((value == null)||(!value.equals(getChangedBy()))) {
                    setChangedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("LocalLastChangedAt")) {
                final Object value = cloudSdkValues.remove("LocalLastChangedAt");
                if ((value == null)||(!value.equals(getChangedOn()))) {
                    setChangedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("HasDraftEntity")) {
                final Object value = cloudSdkValues.remove("HasDraftEntity");
                if ((value == null)||(!value.equals(getHasDraft()))) {
                    setHasDraft(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftEntityCreationDateTime")) {
                final Object value = cloudSdkValues.remove("DraftEntityCreationDateTime");
                if ((value == null)||(!value.equals(getDraftCreatedOn()))) {
                    setDraftCreatedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftEntityLastChangeDateTime")) {
                final Object value = cloudSdkValues.remove("DraftEntityLastChangeDateTime");
                if ((value == null)||(!value.equals(getDraftLastChangedOn()))) {
                    setDraftLastChangedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("HasActiveEntity")) {
                final Object value = cloudSdkValues.remove("HasActiveEntity");
                if ((value == null)||(!value.equals(getHasActive()))) {
                    setHasActive(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("IsActiveEntity")) {
                final Object value = cloudSdkValues.remove("IsActiveEntity");
                if ((value == null)||(!value.equals(getIsActive()))) {
                    setIsActive(((java.lang.Boolean) value));
                }
            }
        }
        // structured properties
        {
            if (cloudSdkValues.containsKey("__EntityControl")) {
                final Object value = cloudSdkValues.remove("__EntityControl");
                if (value instanceof Map) {
                    if (get__EntityControl() == null) {
                        set__EntityControl(new EntityControl());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                    get__EntityControl().fromMap(inputMap);
                }
                if ((value == null)&&(get__EntityControl()!= null)) {
                    set__EntityControl(null);
                }
            }
            if (cloudSdkValues.containsKey("SAP__Messages")) {
                final Object value = cloudSdkValues.remove("SAP__Messages");
                if (value instanceof Iterable) {
                    final LinkedList<SAP__Message> _Messages = new LinkedList<SAP__Message>();
                    for (Object properties: ((Iterable<?> ) value)) {
                        if (properties instanceof Map) {
                            final SAP__Message item = new SAP__Message();
                            @SuppressWarnings("unchecked")
                            final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                            item.fromMap(inputMap);
                            _Messages.add(item);
                        }
                    }
                    set_Messages(_Messages);
                }
                if ((value == null)&&(get_Messages()!= null)) {
                    set_Messages(null);
                }
            }
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("DraftAdministrativeData")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("DraftAdministrativeData");
                if (cloudSdkValue instanceof Map) {
                    if (toDraftAdministrativeData == null) {
                        toDraftAdministrativeData = new DraftAdministrationData();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    toDraftAdministrativeData.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("SiblingEntity")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("SiblingEntity");
                if (cloudSdkValue instanceof Map) {
                    if (toSiblingEntity == null) {
                        toSiblingEntity = new ConsumptionViewForGenerateDdlsl();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    toSiblingEntity.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("_proj")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("_proj");
                if (cloudSdkValue instanceof Map) {
                    if (to_proj == null) {
                        to_proj = new ConsumptionViewForGenerateDdlsp();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    to_proj.fromMap(inputMap);
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return S4CreateCdsMetadataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toDraftAdministrativeData!= null) {
            (cloudSdkValues).put("DraftAdministrativeData", toDraftAdministrativeData);
        }
        if (toSiblingEntity!= null) {
            (cloudSdkValues).put("SiblingEntity", toSiblingEntity);
        }
        if (to_proj!= null) {
            (cloudSdkValues).put("_proj", to_proj);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>DraftAdministrationData</b> entity (one to one). This corresponds to the OData navigation property <b>DraftAdministrativeData</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlsl</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>DraftAdministrativeData</b> is already loaded, the result will contain the <b>DraftAdministrationData</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<DraftAdministrationData> getDraftAdministrativeDataIfPresent() {
        return Option.of(toDraftAdministrativeData);
    }

    /**
     * Overwrites the associated <b>DraftAdministrationData</b> entity for the loaded navigation property <b>DraftAdministrativeData</b>.
     * 
     * @param cloudSdkValue
     *     New <b>DraftAdministrationData</b> entity.
     */
    public void setDraftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
        toDraftAdministrativeData = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>ConsumptionViewForGenerateDdlsl</b> entity (one to one). This corresponds to the OData navigation property <b>SiblingEntity</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlsl</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>SiblingEntity</b> is already loaded, the result will contain the <b>ConsumptionViewForGenerateDdlsl</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<ConsumptionViewForGenerateDdlsl> getSiblingEntityIfPresent() {
        return Option.of(toSiblingEntity);
    }

    /**
     * Overwrites the associated <b>ConsumptionViewForGenerateDdlsl</b> entity for the loaded navigation property <b>SiblingEntity</b>.
     * 
     * @param cloudSdkValue
     *     New <b>ConsumptionViewForGenerateDdlsl</b> entity.
     */
    public void setSiblingEntity(final ConsumptionViewForGenerateDdlsl cloudSdkValue) {
        toSiblingEntity = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>ConsumptionViewForGenerateDdlsp</b> entity (one to one). This corresponds to the OData navigation property <b>_proj</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlsl</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>_proj</b> is already loaded, the result will contain the <b>ConsumptionViewForGenerateDdlsp</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<ConsumptionViewForGenerateDdlsp> getProjIfPresent() {
        return Option.of(to_proj);
    }

    /**
     * Overwrites the associated <b>ConsumptionViewForGenerateDdlsp</b> entity for the loaded navigation property <b>_proj</b>.
     * 
     * @param cloudSdkValue
     *     New <b>ConsumptionViewForGenerateDdlsp</b> entity.
     */
    public void setProj(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
        to_proj = cloudSdkValue;
    }


    /**
     * Helper class to allow for fluent creation of ConsumptionViewForGenerateDdlsl instances.
     * 
     */
    public final static class ConsumptionViewForGenerateDdlslBuilder {

        private DraftAdministrationData toDraftAdministrativeData;
        private ConsumptionViewForGenerateDdlsl toSiblingEntity;
        private ConsumptionViewForGenerateDdlsp to_proj;

        private ConsumptionViewForGenerateDdlsl.ConsumptionViewForGenerateDdlslBuilder toDraftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
            toDraftAdministrativeData = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>DraftAdministrativeData</b> for <b>ConsumptionViewForGenerateDdlsl</b> to single <b>DraftAdministrationData</b>.
         * 
         * @param cloudSdkValue
         *     The DraftAdministrationData to build this ConsumptionViewForGenerateDdlsl with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlsl.ConsumptionViewForGenerateDdlslBuilder draftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
            return toDraftAdministrativeData(cloudSdkValue);
        }

        private ConsumptionViewForGenerateDdlsl.ConsumptionViewForGenerateDdlslBuilder toSiblingEntity(final ConsumptionViewForGenerateDdlsl cloudSdkValue) {
            toSiblingEntity = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>SiblingEntity</b> for <b>ConsumptionViewForGenerateDdlsl</b> to single <b>ConsumptionViewForGenerateDdlsl</b>.
         * 
         * @param cloudSdkValue
         *     The ConsumptionViewForGenerateDdlsl to build this ConsumptionViewForGenerateDdlsl with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlsl.ConsumptionViewForGenerateDdlslBuilder siblingEntity(final ConsumptionViewForGenerateDdlsl cloudSdkValue) {
            return toSiblingEntity(cloudSdkValue);
        }

        private ConsumptionViewForGenerateDdlsl.ConsumptionViewForGenerateDdlslBuilder to_proj(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
            to_proj = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>_proj</b> for <b>ConsumptionViewForGenerateDdlsl</b> to single <b>ConsumptionViewForGenerateDdlsp</b>.
         * 
         * @param cloudSdkValue
         *     The ConsumptionViewForGenerateDdlsp to build this ConsumptionViewForGenerateDdlsl with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlsl.ConsumptionViewForGenerateDdlslBuilder proj(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
            return to_proj(cloudSdkValue);
        }

    }

}
