
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import customer.ai2code.model.s4.services.S4CreateCdsMetadataService;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


/**
 * Consumption view for generate ddls -p<p></p><p>Original entity name from the Odata EDM: <b>zc_genddls_pType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class ConsumptionViewForGenerateDdlsp
    extends VdmEntity<ConsumptionViewForGenerateDdlsp>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.zc_genddls_pType";
    /**
     * Selector for all available fields of ConsumptionViewForGenerateDdlsp.
     * 
     */
    public final static SimpleProperty<ConsumptionViewForGenerateDdlsp> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Projname</b></p>
     * 
     * @return
     *     Project name
     */
    @Nullable
    @ElementName("Projname")
    private java.lang.String projectName;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsp> PROJECT_NAME = new SimpleProperty.String<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "Projname");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Projdesc</b></p>
     * 
     * @return
     *     Project description
     */
    @Nullable
    @ElementName("Projdesc")
    private java.lang.String projectDescription;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsp> PROJECT_DESCRIPTION = new SimpleProperty.String<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "Projdesc");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Withdraft</b></p>
     * 
     * @return
     *     Boolean Variable (X = True, - = False, Space = Unknown)
     */
    @Nullable
    @ElementName("Withdraft")
    private java.lang.Boolean withDraft;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp> WITH_DRAFT = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "Withdraft");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Withadditionalsave</b></p>
     * 
     * @return
     *     Boolean Variable (X = True, - = False, Space = Unknown)
     */
    @Nullable
    @ElementName("Withadditionalsave")
    private java.lang.Boolean withAdditionalSave;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp> WITH_ADDITIONAL_SAVE = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "Withadditionalsave");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Devclass</b></p>
     * 
     * @return
     *     XCO Package: Package
     */
    @Nullable
    @ElementName("Devclass")
    private java.lang.String packageProperty;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsp> PACKAGE_PROPERTY = new SimpleProperty.String<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "Devclass");
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Trkorr</b></p>
     * 
     * @return
     *     XCO: Transport
     */
    @Nullable
    @ElementName("Trkorr")
    private java.lang.String transport;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsp> TRANSPORT = new SimpleProperty.String<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "Trkorr");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Status</b></p>
     * 
     * @return
     *     Active Status
     */
    @Nullable
    @ElementName("Status")
    private java.lang.String activeStatus;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsp> ACTIVE_STATUS = new SimpleProperty.String<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "Status");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedBy</b></p>
     * 
     * @return
     *     Created By User
     */
    @Nullable
    @ElementName("CreatedBy")
    private java.lang.String createdBy;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsp> CREATED_BY = new SimpleProperty.String<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "CreatedBy");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreatedAt</b></p>
     * 
     * @return
     *     Creation Date Time
     */
    @Nullable
    @ElementName("CreatedAt")
    private OffsetDateTime createdOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp> CREATED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "CreatedAt");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LocalLastChangedBy</b></p>
     * 
     * @return
     *     Local Instance Last Changed By User
     */
    @Nullable
    @ElementName("LocalLastChangedBy")
    private java.lang.String changedBy;
    public final static SimpleProperty.String<ConsumptionViewForGenerateDdlsp> CHANGED_BY = new SimpleProperty.String<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "LocalLastChangedBy");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LocalLastChangedAt</b></p>
     * 
     * @return
     *     Local Instance Last Change Date Time
     */
    @Nullable
    @ElementName("LocalLastChangedAt")
    private OffsetDateTime changedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp> CHANGED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "LocalLastChangedAt");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasDraftEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Has draft document
     */
    @Nullable
    @ElementName("HasDraftEntity")
    private java.lang.Boolean hasDraft;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp> HAS_DRAFT = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "HasDraftEntity");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityCreationDateTime</b></p>
     * 
     * @return
     *     Draft Created On
     */
    @Nullable
    @ElementName("DraftEntityCreationDateTime")
    private OffsetDateTime draftCreatedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp> DRAFT_CREATED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "DraftEntityCreationDateTime");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityLastChangeDateTime</b></p>
     * 
     * @return
     *     Draft Last Changed On
     */
    @Nullable
    @ElementName("DraftEntityLastChangeDateTime")
    private OffsetDateTime draftLastChangedOn;
    public final static SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp> DRAFT_LAST_CHANGED_ON = new SimpleProperty.DateTime<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "DraftEntityLastChangeDateTime");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasActiveEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Has active document
     */
    @Nullable
    @ElementName("HasActiveEntity")
    private java.lang.Boolean hasActive;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp> HAS_ACTIVE = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "HasActiveEntity");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>IsActiveEntity</b></p>
     * 
     * @return
     *     Draft - Indicator - Is active document
     */
    @Nullable
    @ElementName("IsActiveEntity")
    private java.lang.Boolean isActive;
    public final static SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp> IS_ACTIVE = new SimpleProperty.Boolean<ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "IsActiveEntity");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__CreateByAssociationControl</b></p>
     * 
     * @return
     *     The __CreateByAssociationControl contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("__CreateByAssociationControl")
    private zc_genddls_pCbAControl __CreateByAssociationControl;
    /**
     * Use with available request builders to apply the <b>__CreateByAssociationControl</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsp, zc_genddls_pCbAControl> _CREATE_BY_ASSOCIATION_CONTROL = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsp, zc_genddls_pCbAControl>(ConsumptionViewForGenerateDdlsp.class, "__CreateByAssociationControl", zc_genddls_pCbAControl.class);
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__EntityControl</b></p>
     * 
     * @return
     *     The __EntityControl contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("__EntityControl")
    private EntityControl __EntityControl;
    /**
     * Use with available request builders to apply the <b>__EntityControl</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsp, EntityControl> _ENTITY_CONTROL = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsp, EntityControl>(ConsumptionViewForGenerateDdlsp.class, "__EntityControl", EntityControl.class);
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__OperationControl</b></p>
     * 
     * @return
     *     The __OperationControl contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("__OperationControl")
    private zc_genddls_pOperationControl __OperationControl;
    /**
     * Use with available request builders to apply the <b>__OperationControl</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsp, zc_genddls_pOperationControl> _OPERATION_CONTROL = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Single<ConsumptionViewForGenerateDdlsp, zc_genddls_pOperationControl>(ConsumptionViewForGenerateDdlsp.class, "__OperationControl", zc_genddls_pOperationControl.class);
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SAP__Messages</b></p>
     * 
     * @return
     *     The _Messages contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("SAP__Messages")
    private java.util.Collection<SAP__Message> _Messages;
    /**
     * Use with available request builders to apply the <b>SAP__Messages</b> complex property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<ConsumptionViewForGenerateDdlsp, SAP__Message> _MESSAGES = new com.sap.cloud.sdk.datamodel.odatav4.core.ComplexProperty.Collection<ConsumptionViewForGenerateDdlsp, SAP__Message>(ConsumptionViewForGenerateDdlsp.class, "SAP__Messages", SAP__Message.class);
    /**
     * Navigation property <b>DraftAdministrativeData</b> for <b>ConsumptionViewForGenerateDdlsp</b> to single <b>DraftAdministrationData</b>.
     * 
     */
    @ElementName("DraftAdministrativeData")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private DraftAdministrationData toDraftAdministrativeData;
    /**
     * Navigation property <b>SiblingEntity</b> for <b>ConsumptionViewForGenerateDdlsp</b> to single <b>ConsumptionViewForGenerateDdlsp</b>.
     * 
     */
    @ElementName("SiblingEntity")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private ConsumptionViewForGenerateDdlsp toSiblingEntity;
    /**
     * Navigation property <b>_log</b> for <b>ConsumptionViewForGenerateDdlsp</b> to multiple <b>ConsumptionViewForGenerateDdlsl</b>.
     * 
     */
    @ElementName("_log")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<ConsumptionViewForGenerateDdlsl> to_log;
    /**
     * Navigation property <b>_source</b> for <b>ConsumptionViewForGenerateDdlsp</b> to multiple <b>ConsumptionViewForGenerateDdlss</b>.
     * 
     */
    @ElementName("_source")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<ConsumptionViewForGenerateDdlss> to_source;
    /**
     * Use with available request builders to apply the <b>DraftAdministrativeData</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsp, DraftAdministrationData> TO_DRAFT_ADMINISTRATIVE_DATA = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsp, DraftAdministrationData>(ConsumptionViewForGenerateDdlsp.class, "DraftAdministrativeData", DraftAdministrationData.class);
    /**
     * Use with available request builders to apply the <b>SiblingEntity</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp> TO_SIBLING_ENTITY = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, "SiblingEntity", ConsumptionViewForGenerateDdlsp.class);
    /**
     * Use with available request builders to apply the <b>_log</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsl> TO__LOG = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsl>(ConsumptionViewForGenerateDdlsp.class, "_log", ConsumptionViewForGenerateDdlsl.class);
    /**
     * Use with available request builders to apply the <b>_source</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlss> TO__SOURCE = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlss>(ConsumptionViewForGenerateDdlsp.class, "_source", ConsumptionViewForGenerateDdlss.class);

    @Nonnull
    @Override
    public Class<ConsumptionViewForGenerateDdlsp> getType() {
        return ConsumptionViewForGenerateDdlsp.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Projname</b></p>
     * 
     * @param projectName
     *     Project name
     */
    public void setProjectName(
        @Nullable
        final java.lang.String projectName) {
        rememberChangedField("Projname", this.projectName);
        this.projectName = projectName;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Projdesc</b></p>
     * 
     * @param projectDescription
     *     Project description
     */
    public void setProjectDescription(
        @Nullable
        final java.lang.String projectDescription) {
        rememberChangedField("Projdesc", this.projectDescription);
        this.projectDescription = projectDescription;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Withdraft</b></p>
     * 
     * @param withDraft
     *     Boolean Variable (X = True, - = False, Space = Unknown)
     */
    public void setWithDraft(
        @Nullable
        final java.lang.Boolean withDraft) {
        rememberChangedField("Withdraft", this.withDraft);
        this.withDraft = withDraft;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Withadditionalsave</b></p>
     * 
     * @param withAdditionalSave
     *     Boolean Variable (X = True, - = False, Space = Unknown)
     */
    public void setWithAdditionalSave(
        @Nullable
        final java.lang.Boolean withAdditionalSave) {
        rememberChangedField("Withadditionalsave", this.withAdditionalSave);
        this.withAdditionalSave = withAdditionalSave;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Devclass</b></p>
     * 
     * @param packageProperty
     *     XCO Package: Package
     */
    public void setPackageProperty(
        @Nullable
        final java.lang.String packageProperty) {
        rememberChangedField("Devclass", this.packageProperty);
        this.packageProperty = packageProperty;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Trkorr</b></p>
     * 
     * @param transport
     *     XCO: Transport
     */
    public void setTransport(
        @Nullable
        final java.lang.String transport) {
        rememberChangedField("Trkorr", this.transport);
        this.transport = transport;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Status</b></p>
     * 
     * @param activeStatus
     *     Active Status
     */
    public void setActiveStatus(
        @Nullable
        final java.lang.String activeStatus) {
        rememberChangedField("Status", this.activeStatus);
        this.activeStatus = activeStatus;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedBy</b></p>
     * 
     * @param createdBy
     *     Created By User
     */
    public void setCreatedBy(
        @Nullable
        final java.lang.String createdBy) {
        rememberChangedField("CreatedBy", this.createdBy);
        this.createdBy = createdBy;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreatedAt</b></p>
     * 
     * @param createdOn
     *     Creation Date Time
     */
    public void setCreatedOn(
        @Nullable
        final OffsetDateTime createdOn) {
        rememberChangedField("CreatedAt", this.createdOn);
        this.createdOn = createdOn;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LocalLastChangedBy</b></p>
     * 
     * @param changedBy
     *     Local Instance Last Changed By User
     */
    public void setChangedBy(
        @Nullable
        final java.lang.String changedBy) {
        rememberChangedField("LocalLastChangedBy", this.changedBy);
        this.changedBy = changedBy;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LocalLastChangedAt</b></p>
     * 
     * @param changedOn
     *     Local Instance Last Change Date Time
     */
    public void setChangedOn(
        @Nullable
        final OffsetDateTime changedOn) {
        rememberChangedField("LocalLastChangedAt", this.changedOn);
        this.changedOn = changedOn;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasDraftEntity</b></p>
     * 
     * @param hasDraft
     *     Draft - Indicator - Has draft document
     */
    public void setHasDraft(
        @Nullable
        final java.lang.Boolean hasDraft) {
        rememberChangedField("HasDraftEntity", this.hasDraft);
        this.hasDraft = hasDraft;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityCreationDateTime</b></p>
     * 
     * @param draftCreatedOn
     *     Draft Created On
     */
    public void setDraftCreatedOn(
        @Nullable
        final OffsetDateTime draftCreatedOn) {
        rememberChangedField("DraftEntityCreationDateTime", this.draftCreatedOn);
        this.draftCreatedOn = draftCreatedOn;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>DraftEntityLastChangeDateTime</b></p>
     * 
     * @param draftLastChangedOn
     *     Draft Last Changed On
     */
    public void setDraftLastChangedOn(
        @Nullable
        final OffsetDateTime draftLastChangedOn) {
        rememberChangedField("DraftEntityLastChangeDateTime", this.draftLastChangedOn);
        this.draftLastChangedOn = draftLastChangedOn;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>HasActiveEntity</b></p>
     * 
     * @param hasActive
     *     Draft - Indicator - Has active document
     */
    public void setHasActive(
        @Nullable
        final java.lang.Boolean hasActive) {
        rememberChangedField("HasActiveEntity", this.hasActive);
        this.hasActive = hasActive;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>IsActiveEntity</b></p>
     * 
     * @param isActive
     *     Draft - Indicator - Is active document
     */
    public void setIsActive(
        @Nullable
        final java.lang.Boolean isActive) {
        rememberChangedField("IsActiveEntity", this.isActive);
        this.isActive = isActive;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__CreateByAssociationControl</b></p>
     * 
     * @param __CreateByAssociationControl
     *     The __CreateByAssociationControl to set.
     */
    public void set__CreateByAssociationControl(
        @Nullable
        final zc_genddls_pCbAControl __CreateByAssociationControl) {
        rememberChangedField("__CreateByAssociationControl", this.__CreateByAssociationControl);
        this.__CreateByAssociationControl = __CreateByAssociationControl;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__EntityControl</b></p>
     * 
     * @param __EntityControl
     *     The __EntityControl to set.
     */
    public void set__EntityControl(
        @Nullable
        final EntityControl __EntityControl) {
        rememberChangedField("__EntityControl", this.__EntityControl);
        this.__EntityControl = __EntityControl;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>__OperationControl</b></p>
     * 
     * @param __OperationControl
     *     The __OperationControl to set.
     */
    public void set__OperationControl(
        @Nullable
        final zc_genddls_pOperationControl __OperationControl) {
        rememberChangedField("__OperationControl", this.__OperationControl);
        this.__OperationControl = __OperationControl;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SAP__Messages</b></p>
     * 
     * @param _Messages
     *     The _Messages to set.
     */
    public void set_Messages(
        @Nullable
        final java.util.Collection<SAP__Message> _Messages) {
        rememberChangedField("SAP__Messages", this._Messages);
        this._Messages = _Messages;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "zc_genddls_p";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("Projname", getProjectName());
        entityKey.addKeyProperty("IsActiveEntity", getIsActive());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("Projname", getProjectName());
        cloudSdkValues.put("Projdesc", getProjectDescription());
        cloudSdkValues.put("Withdraft", getWithDraft());
        cloudSdkValues.put("Withadditionalsave", getWithAdditionalSave());
        cloudSdkValues.put("Devclass", getPackageProperty());
        cloudSdkValues.put("Trkorr", getTransport());
        cloudSdkValues.put("Status", getActiveStatus());
        cloudSdkValues.put("CreatedBy", getCreatedBy());
        cloudSdkValues.put("CreatedAt", getCreatedOn());
        cloudSdkValues.put("LocalLastChangedBy", getChangedBy());
        cloudSdkValues.put("LocalLastChangedAt", getChangedOn());
        cloudSdkValues.put("HasDraftEntity", getHasDraft());
        cloudSdkValues.put("DraftEntityCreationDateTime", getDraftCreatedOn());
        cloudSdkValues.put("DraftEntityLastChangeDateTime", getDraftLastChangedOn());
        cloudSdkValues.put("HasActiveEntity", getHasActive());
        cloudSdkValues.put("IsActiveEntity", getIsActive());
        cloudSdkValues.put("__CreateByAssociationControl", get__CreateByAssociationControl());
        cloudSdkValues.put("__EntityControl", get__EntityControl());
        cloudSdkValues.put("__OperationControl", get__OperationControl());
        cloudSdkValues.put("SAP__Messages", get_Messages());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("Projname")) {
                final Object value = cloudSdkValues.remove("Projname");
                if ((value == null)||(!value.equals(getProjectName()))) {
                    setProjectName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Projdesc")) {
                final Object value = cloudSdkValues.remove("Projdesc");
                if ((value == null)||(!value.equals(getProjectDescription()))) {
                    setProjectDescription(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Withdraft")) {
                final Object value = cloudSdkValues.remove("Withdraft");
                if ((value == null)||(!value.equals(getWithDraft()))) {
                    setWithDraft(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("Withadditionalsave")) {
                final Object value = cloudSdkValues.remove("Withadditionalsave");
                if ((value == null)||(!value.equals(getWithAdditionalSave()))) {
                    setWithAdditionalSave(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("Devclass")) {
                final Object value = cloudSdkValues.remove("Devclass");
                if ((value == null)||(!value.equals(getPackageProperty()))) {
                    setPackageProperty(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Trkorr")) {
                final Object value = cloudSdkValues.remove("Trkorr");
                if ((value == null)||(!value.equals(getTransport()))) {
                    setTransport(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Status")) {
                final Object value = cloudSdkValues.remove("Status");
                if ((value == null)||(!value.equals(getActiveStatus()))) {
                    setActiveStatus(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedBy")) {
                final Object value = cloudSdkValues.remove("CreatedBy");
                if ((value == null)||(!value.equals(getCreatedBy()))) {
                    setCreatedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedAt")) {
                final Object value = cloudSdkValues.remove("CreatedAt");
                if ((value == null)||(!value.equals(getCreatedOn()))) {
                    setCreatedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("LocalLastChangedBy")) {
                final Object value = cloudSdkValues.remove("LocalLastChangedBy");
                if ((value == null)||(!value.equals(getChangedBy()))) {
                    setChangedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("LocalLastChangedAt")) {
                final Object value = cloudSdkValues.remove("LocalLastChangedAt");
                if ((value == null)||(!value.equals(getChangedOn()))) {
                    setChangedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("HasDraftEntity")) {
                final Object value = cloudSdkValues.remove("HasDraftEntity");
                if ((value == null)||(!value.equals(getHasDraft()))) {
                    setHasDraft(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftEntityCreationDateTime")) {
                final Object value = cloudSdkValues.remove("DraftEntityCreationDateTime");
                if ((value == null)||(!value.equals(getDraftCreatedOn()))) {
                    setDraftCreatedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftEntityLastChangeDateTime")) {
                final Object value = cloudSdkValues.remove("DraftEntityLastChangeDateTime");
                if ((value == null)||(!value.equals(getDraftLastChangedOn()))) {
                    setDraftLastChangedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("HasActiveEntity")) {
                final Object value = cloudSdkValues.remove("HasActiveEntity");
                if ((value == null)||(!value.equals(getHasActive()))) {
                    setHasActive(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("IsActiveEntity")) {
                final Object value = cloudSdkValues.remove("IsActiveEntity");
                if ((value == null)||(!value.equals(getIsActive()))) {
                    setIsActive(((java.lang.Boolean) value));
                }
            }
        }
        // structured properties
        {
            if (cloudSdkValues.containsKey("__CreateByAssociationControl")) {
                final Object value = cloudSdkValues.remove("__CreateByAssociationControl");
                if (value instanceof Map) {
                    if (get__CreateByAssociationControl() == null) {
                        set__CreateByAssociationControl(new zc_genddls_pCbAControl());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                    get__CreateByAssociationControl().fromMap(inputMap);
                }
                if ((value == null)&&(get__CreateByAssociationControl()!= null)) {
                    set__CreateByAssociationControl(null);
                }
            }
            if (cloudSdkValues.containsKey("__EntityControl")) {
                final Object value = cloudSdkValues.remove("__EntityControl");
                if (value instanceof Map) {
                    if (get__EntityControl() == null) {
                        set__EntityControl(new EntityControl());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                    get__EntityControl().fromMap(inputMap);
                }
                if ((value == null)&&(get__EntityControl()!= null)) {
                    set__EntityControl(null);
                }
            }
            if (cloudSdkValues.containsKey("__OperationControl")) {
                final Object value = cloudSdkValues.remove("__OperationControl");
                if (value instanceof Map) {
                    if (get__OperationControl() == null) {
                        set__OperationControl(new zc_genddls_pOperationControl());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                    get__OperationControl().fromMap(inputMap);
                }
                if ((value == null)&&(get__OperationControl()!= null)) {
                    set__OperationControl(null);
                }
            }
            if (cloudSdkValues.containsKey("SAP__Messages")) {
                final Object value = cloudSdkValues.remove("SAP__Messages");
                if (value instanceof Iterable) {
                    final LinkedList<SAP__Message> _Messages = new LinkedList<SAP__Message>();
                    for (Object properties: ((Iterable<?> ) value)) {
                        if (properties instanceof Map) {
                            final SAP__Message item = new SAP__Message();
                            @SuppressWarnings("unchecked")
                            final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                            item.fromMap(inputMap);
                            _Messages.add(item);
                        }
                    }
                    set_Messages(_Messages);
                }
                if ((value == null)&&(get_Messages()!= null)) {
                    set_Messages(null);
                }
            }
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("DraftAdministrativeData")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("DraftAdministrativeData");
                if (cloudSdkValue instanceof Map) {
                    if (toDraftAdministrativeData == null) {
                        toDraftAdministrativeData = new DraftAdministrationData();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    toDraftAdministrativeData.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("SiblingEntity")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("SiblingEntity");
                if (cloudSdkValue instanceof Map) {
                    if (toSiblingEntity == null) {
                        toSiblingEntity = new ConsumptionViewForGenerateDdlsp();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    toSiblingEntity.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("_log")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("_log");
                if (cloudSdkValue instanceof Iterable) {
                    if (to_log == null) {
                        to_log = Lists.newArrayList();
                    } else {
                        to_log = Lists.newArrayList(to_log);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) cloudSdkValue)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        ConsumptionViewForGenerateDdlsl entity;
                        if (to_log.size()>i) {
                            entity = to_log.get(i);
                        } else {
                            entity = new ConsumptionViewForGenerateDdlsl();
                            to_log.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
            if ((cloudSdkValues).containsKey("_source")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("_source");
                if (cloudSdkValue instanceof Iterable) {
                    if (to_source == null) {
                        to_source = Lists.newArrayList();
                    } else {
                        to_source = Lists.newArrayList(to_source);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) cloudSdkValue)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        ConsumptionViewForGenerateDdlss entity;
                        if (to_source.size()>i) {
                            entity = to_source.get(i);
                        } else {
                            entity = new ConsumptionViewForGenerateDdlss();
                            to_source.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return S4CreateCdsMetadataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toDraftAdministrativeData!= null) {
            (cloudSdkValues).put("DraftAdministrativeData", toDraftAdministrativeData);
        }
        if (toSiblingEntity!= null) {
            (cloudSdkValues).put("SiblingEntity", toSiblingEntity);
        }
        if (to_log!= null) {
            (cloudSdkValues).put("_log", to_log);
        }
        if (to_source!= null) {
            (cloudSdkValues).put("_source", to_source);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>DraftAdministrationData</b> entity (one to one). This corresponds to the OData navigation property <b>DraftAdministrativeData</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlsp</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>DraftAdministrativeData</b> is already loaded, the result will contain the <b>DraftAdministrationData</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<DraftAdministrationData> getDraftAdministrativeDataIfPresent() {
        return Option.of(toDraftAdministrativeData);
    }

    /**
     * Overwrites the associated <b>DraftAdministrationData</b> entity for the loaded navigation property <b>DraftAdministrativeData</b>.
     * 
     * @param cloudSdkValue
     *     New <b>DraftAdministrationData</b> entity.
     */
    public void setDraftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
        toDraftAdministrativeData = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>ConsumptionViewForGenerateDdlsp</b> entity (one to one). This corresponds to the OData navigation property <b>SiblingEntity</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlsp</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>SiblingEntity</b> is already loaded, the result will contain the <b>ConsumptionViewForGenerateDdlsp</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<ConsumptionViewForGenerateDdlsp> getSiblingEntityIfPresent() {
        return Option.of(toSiblingEntity);
    }

    /**
     * Overwrites the associated <b>ConsumptionViewForGenerateDdlsp</b> entity for the loaded navigation property <b>SiblingEntity</b>.
     * 
     * @param cloudSdkValue
     *     New <b>ConsumptionViewForGenerateDdlsp</b> entity.
     */
    public void setSiblingEntity(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
        toSiblingEntity = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>ConsumptionViewForGenerateDdlsl</b> entities (one to many). This corresponds to the OData navigation property <b>_log</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlsp</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>_log</b> is already loaded, the result will contain the <b>ConsumptionViewForGenerateDdlsl</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<ConsumptionViewForGenerateDdlsl>> getLogIfPresent() {
        return Option.of(to_log);
    }

    /**
     * Overwrites the list of associated <b>ConsumptionViewForGenerateDdlsl</b> entities for the loaded navigation property <b>_log</b>.
     * <p>
     * If the navigation property <b>_log</b> of a queried <b>ConsumptionViewForGenerateDdlsp</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param cloudSdkValue
     *     List of <b>ConsumptionViewForGenerateDdlsl</b> entities.
     */
    public void setLog(
        @Nonnull
        final List<ConsumptionViewForGenerateDdlsl> cloudSdkValue) {
        if (to_log == null) {
            to_log = Lists.newArrayList();
        }
        to_log.clear();
        to_log.addAll(cloudSdkValue);
    }

    /**
     * Adds elements to the list of associated <b>ConsumptionViewForGenerateDdlsl</b> entities. This corresponds to the OData navigation property <b>_log</b>.
     * <p>
     * If the navigation property <b>_log</b> of a queried <b>ConsumptionViewForGenerateDdlsp</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>ConsumptionViewForGenerateDdlsl</b> entities.
     */
    public void addLog(ConsumptionViewForGenerateDdlsl... entity) {
        if (to_log == null) {
            to_log = Lists.newArrayList();
        }
        to_log.addAll(Lists.newArrayList(entity));
    }

    /**
     * Retrieval of associated <b>ConsumptionViewForGenerateDdlss</b> entities (one to many). This corresponds to the OData navigation property <b>_source</b>.
     * <p>
     * If the navigation property for an entity <b>ConsumptionViewForGenerateDdlsp</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>_source</b> is already loaded, the result will contain the <b>ConsumptionViewForGenerateDdlss</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<ConsumptionViewForGenerateDdlss>> getSourceIfPresent() {
        return Option.of(to_source);
    }

    /**
     * Overwrites the list of associated <b>ConsumptionViewForGenerateDdlss</b> entities for the loaded navigation property <b>_source</b>.
     * <p>
     * If the navigation property <b>_source</b> of a queried <b>ConsumptionViewForGenerateDdlsp</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param cloudSdkValue
     *     List of <b>ConsumptionViewForGenerateDdlss</b> entities.
     */
    public void setSource(
        @Nonnull
        final List<ConsumptionViewForGenerateDdlss> cloudSdkValue) {
        if (to_source == null) {
            to_source = Lists.newArrayList();
        }
        to_source.clear();
        to_source.addAll(cloudSdkValue);
    }

    /**
     * Adds elements to the list of associated <b>ConsumptionViewForGenerateDdlss</b> entities. This corresponds to the OData navigation property <b>_source</b>.
     * <p>
     * If the navigation property <b>_source</b> of a queried <b>ConsumptionViewForGenerateDdlsp</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>ConsumptionViewForGenerateDdlss</b> entities.
     */
    public void addSource(ConsumptionViewForGenerateDdlss... entity) {
        if (to_source == null) {
            to_source = Lists.newArrayList();
        }
        to_source.addAll(Lists.newArrayList(entity));
    }

    /**
     * Action that can be applied to any entity object of this class.</p>
     * 
     * @return
     *     Action object prepared with the given parameters to be applied to any entity object of this class.</p> To execute it use the {@code service.forEntity(entity).applyAction(thisAction)} API.
     */
    @Nonnull
    public static com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp> activeCDS() {
        final Map<java.lang.String, Object> parameters = Collections.emptyMap();
        return new com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, ConsumptionViewForGenerateDdlsp.class, "com.sap.gateway.srvd.zsrvd_genddls.v0001.activeCDS", parameters);
    }

    /**
     * Action that can be applied to any entity object of this class.</p>
     * 
     * @return
     *     Action object prepared with the given parameters to be applied to any entity object of this class.</p> To execute it use the {@code service.forEntity(entity).applyAction(thisAction)} API.
     */
    @Nonnull
    public static com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp> activate() {
        final Map<java.lang.String, Object> parameters = Collections.emptyMap();
        return new com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, ConsumptionViewForGenerateDdlsp.class, "com.sap.gateway.srvd.zsrvd_genddls.v0001.Activate", parameters);
    }

    /**
     * Action that can be applied to any entity object of this class.</p>
     * 
     * @param preserveChanges
     *     Constraints: Not nullable<p>Original parameter name from the Odata EDM: <b>PreserveChanges</b></p>
     * @return
     *     Action object prepared with the given parameters to be applied to any entity object of this class.</p> To execute it use the {@code service.forEntity(entity).applyAction(thisAction)} API.
     */
    @Nonnull
    public static com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp> edit(
        @Nonnull
        final java.lang.Boolean preserveChanges) {
        final Map<java.lang.String, Object> parameters = new HashMap<java.lang.String, Object>();
        parameters.put("PreserveChanges", preserveChanges);
        return new com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, ConsumptionViewForGenerateDdlsp>(ConsumptionViewForGenerateDdlsp.class, ConsumptionViewForGenerateDdlsp.class, "com.sap.gateway.srvd.zsrvd_genddls.v0001.Edit", parameters);
    }

    /**
     * Action that can be applied to any entity object of this class.</p>
     * 
     * @return
     *     Action object prepared with the given parameters to be applied to any entity object of this class.</p> To execute it use the {@code service.forEntity(entity).applyAction(thisAction)} API.
     */
    @Nonnull
    public static com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, Void> prepare() {
        final Map<java.lang.String, Object> parameters = Collections.emptyMap();
        return new com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, Void>(ConsumptionViewForGenerateDdlsp.class, Void.class, "com.sap.gateway.srvd.zsrvd_genddls.v0001.Prepare", parameters);
    }

    /**
     * Action that can be applied to a collection of entities of this class.</p>
     * 
     * @param pROJNAME
     *     Constraints: Not nullable, Maximum length: 30<p>Original parameter name from the Odata EDM: <b>PROJNAME</b></p>
     * @param wITHADDITIONALSAVE
     *     Constraints: Not nullable<p>Original parameter name from the Odata EDM: <b>WITHADDITIONALSAVE</b></p>
     * @param dEVCLASS
     *     Constraints: Not nullable, Maximum length: 30<p>Original parameter name from the Odata EDM: <b>DEVCLASS</b></p>
     * @param wITHDRAFT
     *     Constraints: Not nullable<p>Original parameter name from the Odata EDM: <b>WITHDRAFT</b></p>
     * @param _SOURCE
     *     Constraints: Not nullable<p>Original parameter name from the Odata EDM: <b>_SOURCE</b></p>
     * @param pROJDESC
     *     Constraints: Not nullable, Maximum length: 40<p>Original parameter name from the Odata EDM: <b>PROJDESC</b></p>
     * @param tRKORR
     *     Constraints: Not nullable, Maximum length: 20<p>Original parameter name from the Odata EDM: <b>TRKORR</b></p>
     * @return
     *     Action object prepared with the given parameters to be applied to a collection of entities of this class.</p> To execute it use the {@code service.forEntity(entity).applyAction(thisAction)} API.
     */
    @Nonnull
    public static com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.CollectionToCollection<ConsumptionViewForGenerateDdlsp, ZSGEN_DDLS_RESPONSE> autoActiveCDS(
        @Nonnull
        final java.lang.String pROJNAME,
        @Nonnull
        final java.lang.String pROJDESC,
        @Nonnull
        final java.lang.Boolean wITHDRAFT,
        @Nonnull
        final java.lang.Boolean wITHADDITIONALSAVE,
        @Nonnull
        final java.lang.String dEVCLASS,
        @Nonnull
        final java.lang.String tRKORR,
        @Nonnull
        final java.util.Collection<ZSGEN_DDLS_SOURCE_LIST> _SOURCE) {
        final Map<java.lang.String, Object> parameters = new HashMap<java.lang.String, Object>();
        parameters.put("PROJNAME", pROJNAME);
        parameters.put("PROJDESC", pROJDESC);
        parameters.put("WITHDRAFT", wITHDRAFT);
        parameters.put("WITHADDITIONALSAVE", wITHADDITIONALSAVE);
        parameters.put("DEVCLASS", dEVCLASS);
        parameters.put("TRKORR", tRKORR);
        parameters.put("_SOURCE", _SOURCE);
        return new com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.CollectionToCollection<ConsumptionViewForGenerateDdlsp, ZSGEN_DDLS_RESPONSE>(ConsumptionViewForGenerateDdlsp.class, ZSGEN_DDLS_RESPONSE.class, "com.sap.gateway.srvd.zsrvd_genddls.v0001.autoActiveCDS", parameters);
    }

    /**
     * Action that can be applied to any entity object of this class.</p>
     * 
     * @return
     *     Action object prepared with the given parameters to be applied to any entity object of this class.</p> To execute it use the {@code service.forEntity(entity).applyAction(thisAction)} API.
     */
    @Nonnull
    public static com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, Void> resume() {
        final Map<java.lang.String, Object> parameters = Collections.emptyMap();
        return new com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, Void>(ConsumptionViewForGenerateDdlsp.class, Void.class, "com.sap.gateway.srvd.zsrvd_genddls.v0001.Resume", parameters);
    }

    /**
     * Action that can be applied to any entity object of this class.</p>
     * 
     * @return
     *     Action object prepared with the given parameters to be applied to any entity object of this class.</p> To execute it use the {@code service.forEntity(entity).applyAction(thisAction)} API.
     */
    @Nonnull
    public static com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, Void> discard() {
        final Map<java.lang.String, Object> parameters = Collections.emptyMap();
        return new com.sap.cloud.sdk.datamodel.odatav4.core.BoundAction.SingleToSingle<ConsumptionViewForGenerateDdlsp, Void>(ConsumptionViewForGenerateDdlsp.class, Void.class, "com.sap.gateway.srvd.zsrvd_genddls.v0001.Discard", parameters);
    }


    /**
     * Helper class to allow for fluent creation of ConsumptionViewForGenerateDdlsp instances.
     * 
     */
    public final static class ConsumptionViewForGenerateDdlspBuilder {

        private DraftAdministrationData toDraftAdministrativeData;
        private ConsumptionViewForGenerateDdlsp toSiblingEntity;
        private List<ConsumptionViewForGenerateDdlsl> to_log = Lists.newArrayList();
        private List<ConsumptionViewForGenerateDdlss> to_source = Lists.newArrayList();

        private ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder toDraftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
            toDraftAdministrativeData = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>DraftAdministrativeData</b> for <b>ConsumptionViewForGenerateDdlsp</b> to single <b>DraftAdministrationData</b>.
         * 
         * @param cloudSdkValue
         *     The DraftAdministrationData to build this ConsumptionViewForGenerateDdlsp with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder draftAdministrativeData(final DraftAdministrationData cloudSdkValue) {
            return toDraftAdministrativeData(cloudSdkValue);
        }

        private ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder toSiblingEntity(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
            toSiblingEntity = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>SiblingEntity</b> for <b>ConsumptionViewForGenerateDdlsp</b> to single <b>ConsumptionViewForGenerateDdlsp</b>.
         * 
         * @param cloudSdkValue
         *     The ConsumptionViewForGenerateDdlsp to build this ConsumptionViewForGenerateDdlsp with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder siblingEntity(final ConsumptionViewForGenerateDdlsp cloudSdkValue) {
            return toSiblingEntity(cloudSdkValue);
        }

        private ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder to_log(final List<ConsumptionViewForGenerateDdlsl> cloudSdkValue) {
            to_log.addAll(cloudSdkValue);
            return this;
        }

        /**
         * Navigation property <b>_log</b> for <b>ConsumptionViewForGenerateDdlsp</b> to multiple <b>ConsumptionViewForGenerateDdlsl</b>.
         * 
         * @param cloudSdkValue
         *     The ConsumptionViewForGenerateDdlsls to build this ConsumptionViewForGenerateDdlsp with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder log(ConsumptionViewForGenerateDdlsl... cloudSdkValue) {
            return to_log(Lists.newArrayList(cloudSdkValue));
        }

        private ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder to_source(final List<ConsumptionViewForGenerateDdlss> cloudSdkValue) {
            to_source.addAll(cloudSdkValue);
            return this;
        }

        /**
         * Navigation property <b>_source</b> for <b>ConsumptionViewForGenerateDdlsp</b> to multiple <b>ConsumptionViewForGenerateDdlss</b>.
         * 
         * @param cloudSdkValue
         *     The ConsumptionViewForGenerateDdlsss to build this ConsumptionViewForGenerateDdlsp with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ConsumptionViewForGenerateDdlsp.ConsumptionViewForGenerateDdlspBuilder source(ConsumptionViewForGenerateDdlss... cloudSdkValue) {
            return to_source(Lists.newArrayList(cloudSdkValue));
        }

    }

}
