
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import customer.ai2code.model.s4.services.S4CreateCdsMetadataService;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Draft Administration Data<p></p><p>Original entity name from the Odata EDM: <b>I_DraftAdministrativeDataType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class DraftAdministrationData
    extends VdmEntity<DraftAdministrationData>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.I_DraftAdministrativeDataType";
    /**
     * Selector for all available fields of DraftAdministrationData.
     * 
     */
    public final static SimpleProperty<DraftAdministrationData> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftUUID</b></p>
     * 
     * @return
     *     Draft (Technical ID)
     */
    @Nullable
    @ElementName("DraftUUID")
    private UUID draftTechnicalID;
    public final static SimpleProperty.Guid<DraftAdministrationData> DRAFT_TECHNICAL_ID = new SimpleProperty.Guid<DraftAdministrationData>(DraftAdministrationData.class, "DraftUUID");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>DraftEntityType</b></p>
     * 
     * @return
     *     Draft Entity ID
     */
    @Nullable
    @ElementName("DraftEntityType")
    private java.lang.String draftEntityID;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_ENTITY_ID = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "DraftEntityType");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreationDateTime</b></p>
     * 
     * @return
     *     Draft Created On
     */
    @Nullable
    @ElementName("CreationDateTime")
    private OffsetDateTime draftCreatedOn;
    public final static SimpleProperty.DateTime<DraftAdministrationData> DRAFT_CREATED_ON = new SimpleProperty.DateTime<DraftAdministrationData>(DraftAdministrationData.class, "CreationDateTime");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedByUser</b></p>
     * 
     * @return
     *     Draft Created By
     */
    @Nullable
    @ElementName("CreatedByUser")
    private java.lang.String draftCreatedBy;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_CREATED_BY = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "CreatedByUser");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LastChangeDateTime</b></p>
     * 
     * @return
     *     Draft Last Changed On
     */
    @Nullable
    @ElementName("LastChangeDateTime")
    private OffsetDateTime draftLastChangedOn;
    public final static SimpleProperty.DateTime<DraftAdministrationData> DRAFT_LAST_CHANGED_ON = new SimpleProperty.DateTime<DraftAdministrationData>(DraftAdministrationData.class, "LastChangeDateTime");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LastChangedByUser</b></p>
     * 
     * @return
     *     Draft Last Changed By
     */
    @Nullable
    @ElementName("LastChangedByUser")
    private java.lang.String draftLastChangedBy;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_LAST_CHANGED_BY = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "LastChangedByUser");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>DraftAccessType</b></p>
     * 
     * @return
     *     Draft Access Type
     */
    @Nullable
    @ElementName("DraftAccessType")
    private java.lang.String draftAccessType;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_ACCESS_TYPE = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "DraftAccessType");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>ProcessingStartDateTime</b></p>
     * 
     * @return
     *     Draft In Process Since
     */
    @Nullable
    @ElementName("ProcessingStartDateTime")
    private OffsetDateTime draftInProcessSince;
    public final static SimpleProperty.DateTime<DraftAdministrationData> DRAFT_IN_PROCESS_SINCE = new SimpleProperty.DateTime<DraftAdministrationData>(DraftAdministrationData.class, "ProcessingStartDateTime");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>InProcessByUser</b></p>
     * 
     * @return
     *     Draft In Process By
     */
    @Nullable
    @ElementName("InProcessByUser")
    private java.lang.String draftInProcessBy;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_IN_PROCESS_BY = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "InProcessByUser");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsKeptByUser</b></p>
     * 
     * @return
     *     Draft Is Kept By User
     */
    @Nullable
    @ElementName("DraftIsKeptByUser")
    private java.lang.Boolean draftIsKeptByUser;
    public final static SimpleProperty.Boolean<DraftAdministrationData> DRAFT_IS_KEPT_BY_USER = new SimpleProperty.Boolean<DraftAdministrationData>(DraftAdministrationData.class, "DraftIsKeptByUser");
    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>EnqueueStartDateTime</b></p>
     * 
     * @return
     *     Draft Locked Since
     */
    @Nullable
    @ElementName("EnqueueStartDateTime")
    private OffsetDateTime draftLockedSince;
    public final static SimpleProperty.DateTime<DraftAdministrationData> DRAFT_LOCKED_SINCE = new SimpleProperty.DateTime<DraftAdministrationData>(DraftAdministrationData.class, "EnqueueStartDateTime");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsCreatedByMe</b></p>
     * 
     * @return
     *     Draft Created By Me
     */
    @Nullable
    @ElementName("DraftIsCreatedByMe")
    private java.lang.Boolean draftCreatedByMe;
    public final static SimpleProperty.Boolean<DraftAdministrationData> DRAFT_CREATED_BY_ME = new SimpleProperty.Boolean<DraftAdministrationData>(DraftAdministrationData.class, "DraftIsCreatedByMe");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsLastChangedByMe</b></p>
     * 
     * @return
     *     Draft Last Changed By Me
     */
    @Nullable
    @ElementName("DraftIsLastChangedByMe")
    private java.lang.Boolean draftLastChangedByMe;
    public final static SimpleProperty.Boolean<DraftAdministrationData> DRAFT_LAST_CHANGED_BY_ME = new SimpleProperty.Boolean<DraftAdministrationData>(DraftAdministrationData.class, "DraftIsLastChangedByMe");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsProcessedByMe</b></p>
     * 
     * @return
     *     Draft In Process By Me
     */
    @Nullable
    @ElementName("DraftIsProcessedByMe")
    private java.lang.Boolean draftInProcessByMe;
    public final static SimpleProperty.Boolean<DraftAdministrationData> DRAFT_IN_PROCESS_BY_ME = new SimpleProperty.Boolean<DraftAdministrationData>(DraftAdministrationData.class, "DraftIsProcessedByMe");
    /**
     * Constraints: Not nullable, Maximum length: 80 <p>Original property name from the Odata EDM: <b>CreatedByUserDescription</b></p>
     * 
     * @return
     *     Draft Created By (Description)
     */
    @Nullable
    @ElementName("CreatedByUserDescription")
    private java.lang.String draftCreatedByDescription;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_CREATED_BY_DESCRIPTION = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "CreatedByUserDescription");
    /**
     * Constraints: Not nullable, Maximum length: 80 <p>Original property name from the Odata EDM: <b>LastChangedByUserDescription</b></p>
     * 
     * @return
     *     Draft Last Changed By (Description)
     */
    @Nullable
    @ElementName("LastChangedByUserDescription")
    private java.lang.String draftLastChangedByDescription;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_LAST_CHANGED_BY_DESCRIPTION = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "LastChangedByUserDescription");
    /**
     * Constraints: Not nullable, Maximum length: 80 <p>Original property name from the Odata EDM: <b>InProcessByUserDescription</b></p>
     * 
     * @return
     *     Draft In Process By (Description)
     */
    @Nullable
    @ElementName("InProcessByUserDescription")
    private java.lang.String draftInProcessByDescription;
    public final static SimpleProperty.String<DraftAdministrationData> DRAFT_IN_PROCESS_BY_DESCRIPTION = new SimpleProperty.String<DraftAdministrationData>(DraftAdministrationData.class, "InProcessByUserDescription");

    @Nonnull
    @Override
    public Class<DraftAdministrationData> getType() {
        return DraftAdministrationData.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftUUID</b></p>
     * 
     * @param draftTechnicalID
     *     Draft (Technical ID)
     */
    public void setDraftTechnicalID(
        @Nullable
        final UUID draftTechnicalID) {
        rememberChangedField("DraftUUID", this.draftTechnicalID);
        this.draftTechnicalID = draftTechnicalID;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>DraftEntityType</b></p>
     * 
     * @param draftEntityID
     *     Draft Entity ID
     */
    public void setDraftEntityID(
        @Nullable
        final java.lang.String draftEntityID) {
        rememberChangedField("DraftEntityType", this.draftEntityID);
        this.draftEntityID = draftEntityID;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>CreationDateTime</b></p>
     * 
     * @param draftCreatedOn
     *     Draft Created On
     */
    public void setDraftCreatedOn(
        @Nullable
        final OffsetDateTime draftCreatedOn) {
        rememberChangedField("CreationDateTime", this.draftCreatedOn);
        this.draftCreatedOn = draftCreatedOn;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>CreatedByUser</b></p>
     * 
     * @param draftCreatedBy
     *     Draft Created By
     */
    public void setDraftCreatedBy(
        @Nullable
        final java.lang.String draftCreatedBy) {
        rememberChangedField("CreatedByUser", this.draftCreatedBy);
        this.draftCreatedBy = draftCreatedBy;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>LastChangeDateTime</b></p>
     * 
     * @param draftLastChangedOn
     *     Draft Last Changed On
     */
    public void setDraftLastChangedOn(
        @Nullable
        final OffsetDateTime draftLastChangedOn) {
        rememberChangedField("LastChangeDateTime", this.draftLastChangedOn);
        this.draftLastChangedOn = draftLastChangedOn;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>LastChangedByUser</b></p>
     * 
     * @param draftLastChangedBy
     *     Draft Last Changed By
     */
    public void setDraftLastChangedBy(
        @Nullable
        final java.lang.String draftLastChangedBy) {
        rememberChangedField("LastChangedByUser", this.draftLastChangedBy);
        this.draftLastChangedBy = draftLastChangedBy;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>DraftAccessType</b></p>
     * 
     * @param draftAccessType
     *     Draft Access Type
     */
    public void setDraftAccessType(
        @Nullable
        final java.lang.String draftAccessType) {
        rememberChangedField("DraftAccessType", this.draftAccessType);
        this.draftAccessType = draftAccessType;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>ProcessingStartDateTime</b></p>
     * 
     * @param draftInProcessSince
     *     Draft In Process Since
     */
    public void setDraftInProcessSince(
        @Nullable
        final OffsetDateTime draftInProcessSince) {
        rememberChangedField("ProcessingStartDateTime", this.draftInProcessSince);
        this.draftInProcessSince = draftInProcessSince;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>InProcessByUser</b></p>
     * 
     * @param draftInProcessBy
     *     Draft In Process By
     */
    public void setDraftInProcessBy(
        @Nullable
        final java.lang.String draftInProcessBy) {
        rememberChangedField("InProcessByUser", this.draftInProcessBy);
        this.draftInProcessBy = draftInProcessBy;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsKeptByUser</b></p>
     * 
     * @param draftIsKeptByUser
     *     Draft Is Kept By User
     */
    public void setDraftIsKeptByUser(
        @Nullable
        final java.lang.Boolean draftIsKeptByUser) {
        rememberChangedField("DraftIsKeptByUser", this.draftIsKeptByUser);
        this.draftIsKeptByUser = draftIsKeptByUser;
    }

    /**
     * Constraints: Nullable, Precision: 7 <p>Original property name from the Odata EDM: <b>EnqueueStartDateTime</b></p>
     * 
     * @param draftLockedSince
     *     Draft Locked Since
     */
    public void setDraftLockedSince(
        @Nullable
        final OffsetDateTime draftLockedSince) {
        rememberChangedField("EnqueueStartDateTime", this.draftLockedSince);
        this.draftLockedSince = draftLockedSince;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsCreatedByMe</b></p>
     * 
     * @param draftCreatedByMe
     *     Draft Created By Me
     */
    public void setDraftCreatedByMe(
        @Nullable
        final java.lang.Boolean draftCreatedByMe) {
        rememberChangedField("DraftIsCreatedByMe", this.draftCreatedByMe);
        this.draftCreatedByMe = draftCreatedByMe;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsLastChangedByMe</b></p>
     * 
     * @param draftLastChangedByMe
     *     Draft Last Changed By Me
     */
    public void setDraftLastChangedByMe(
        @Nullable
        final java.lang.Boolean draftLastChangedByMe) {
        rememberChangedField("DraftIsLastChangedByMe", this.draftLastChangedByMe);
        this.draftLastChangedByMe = draftLastChangedByMe;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>DraftIsProcessedByMe</b></p>
     * 
     * @param draftInProcessByMe
     *     Draft In Process By Me
     */
    public void setDraftInProcessByMe(
        @Nullable
        final java.lang.Boolean draftInProcessByMe) {
        rememberChangedField("DraftIsProcessedByMe", this.draftInProcessByMe);
        this.draftInProcessByMe = draftInProcessByMe;
    }

    /**
     * Constraints: Not nullable, Maximum length: 80 <p>Original property name from the Odata EDM: <b>CreatedByUserDescription</b></p>
     * 
     * @param draftCreatedByDescription
     *     Draft Created By (Description)
     */
    public void setDraftCreatedByDescription(
        @Nullable
        final java.lang.String draftCreatedByDescription) {
        rememberChangedField("CreatedByUserDescription", this.draftCreatedByDescription);
        this.draftCreatedByDescription = draftCreatedByDescription;
    }

    /**
     * Constraints: Not nullable, Maximum length: 80 <p>Original property name from the Odata EDM: <b>LastChangedByUserDescription</b></p>
     * 
     * @param draftLastChangedByDescription
     *     Draft Last Changed By (Description)
     */
    public void setDraftLastChangedByDescription(
        @Nullable
        final java.lang.String draftLastChangedByDescription) {
        rememberChangedField("LastChangedByUserDescription", this.draftLastChangedByDescription);
        this.draftLastChangedByDescription = draftLastChangedByDescription;
    }

    /**
     * Constraints: Not nullable, Maximum length: 80 <p>Original property name from the Odata EDM: <b>InProcessByUserDescription</b></p>
     * 
     * @param draftInProcessByDescription
     *     Draft In Process By (Description)
     */
    public void setDraftInProcessByDescription(
        @Nullable
        final java.lang.String draftInProcessByDescription) {
        rememberChangedField("InProcessByUserDescription", this.draftInProcessByDescription);
        this.draftInProcessByDescription = draftInProcessByDescription;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "I_DraftAdministrativeData";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("DraftUUID", getDraftTechnicalID());
        entityKey.addKeyProperty("DraftEntityType", getDraftEntityID());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("DraftUUID", getDraftTechnicalID());
        cloudSdkValues.put("DraftEntityType", getDraftEntityID());
        cloudSdkValues.put("CreationDateTime", getDraftCreatedOn());
        cloudSdkValues.put("CreatedByUser", getDraftCreatedBy());
        cloudSdkValues.put("LastChangeDateTime", getDraftLastChangedOn());
        cloudSdkValues.put("LastChangedByUser", getDraftLastChangedBy());
        cloudSdkValues.put("DraftAccessType", getDraftAccessType());
        cloudSdkValues.put("ProcessingStartDateTime", getDraftInProcessSince());
        cloudSdkValues.put("InProcessByUser", getDraftInProcessBy());
        cloudSdkValues.put("DraftIsKeptByUser", getDraftIsKeptByUser());
        cloudSdkValues.put("EnqueueStartDateTime", getDraftLockedSince());
        cloudSdkValues.put("DraftIsCreatedByMe", getDraftCreatedByMe());
        cloudSdkValues.put("DraftIsLastChangedByMe", getDraftLastChangedByMe());
        cloudSdkValues.put("DraftIsProcessedByMe", getDraftInProcessByMe());
        cloudSdkValues.put("CreatedByUserDescription", getDraftCreatedByDescription());
        cloudSdkValues.put("LastChangedByUserDescription", getDraftLastChangedByDescription());
        cloudSdkValues.put("InProcessByUserDescription", getDraftInProcessByDescription());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("DraftUUID")) {
                final Object value = cloudSdkValues.remove("DraftUUID");
                if ((value == null)||(!value.equals(getDraftTechnicalID()))) {
                    setDraftTechnicalID(((UUID) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftEntityType")) {
                final Object value = cloudSdkValues.remove("DraftEntityType");
                if ((value == null)||(!value.equals(getDraftEntityID()))) {
                    setDraftEntityID(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CreationDateTime")) {
                final Object value = cloudSdkValues.remove("CreationDateTime");
                if ((value == null)||(!value.equals(getDraftCreatedOn()))) {
                    setDraftCreatedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedByUser")) {
                final Object value = cloudSdkValues.remove("CreatedByUser");
                if ((value == null)||(!value.equals(getDraftCreatedBy()))) {
                    setDraftCreatedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("LastChangeDateTime")) {
                final Object value = cloudSdkValues.remove("LastChangeDateTime");
                if ((value == null)||(!value.equals(getDraftLastChangedOn()))) {
                    setDraftLastChangedOn(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("LastChangedByUser")) {
                final Object value = cloudSdkValues.remove("LastChangedByUser");
                if ((value == null)||(!value.equals(getDraftLastChangedBy()))) {
                    setDraftLastChangedBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftAccessType")) {
                final Object value = cloudSdkValues.remove("DraftAccessType");
                if ((value == null)||(!value.equals(getDraftAccessType()))) {
                    setDraftAccessType(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ProcessingStartDateTime")) {
                final Object value = cloudSdkValues.remove("ProcessingStartDateTime");
                if ((value == null)||(!value.equals(getDraftInProcessSince()))) {
                    setDraftInProcessSince(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("InProcessByUser")) {
                final Object value = cloudSdkValues.remove("InProcessByUser");
                if ((value == null)||(!value.equals(getDraftInProcessBy()))) {
                    setDraftInProcessBy(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftIsKeptByUser")) {
                final Object value = cloudSdkValues.remove("DraftIsKeptByUser");
                if ((value == null)||(!value.equals(getDraftIsKeptByUser()))) {
                    setDraftIsKeptByUser(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("EnqueueStartDateTime")) {
                final Object value = cloudSdkValues.remove("EnqueueStartDateTime");
                if ((value == null)||(!value.equals(getDraftLockedSince()))) {
                    setDraftLockedSince(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftIsCreatedByMe")) {
                final Object value = cloudSdkValues.remove("DraftIsCreatedByMe");
                if ((value == null)||(!value.equals(getDraftCreatedByMe()))) {
                    setDraftCreatedByMe(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftIsLastChangedByMe")) {
                final Object value = cloudSdkValues.remove("DraftIsLastChangedByMe");
                if ((value == null)||(!value.equals(getDraftLastChangedByMe()))) {
                    setDraftLastChangedByMe(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("DraftIsProcessedByMe")) {
                final Object value = cloudSdkValues.remove("DraftIsProcessedByMe");
                if ((value == null)||(!value.equals(getDraftInProcessByMe()))) {
                    setDraftInProcessByMe(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("CreatedByUserDescription")) {
                final Object value = cloudSdkValues.remove("CreatedByUserDescription");
                if ((value == null)||(!value.equals(getDraftCreatedByDescription()))) {
                    setDraftCreatedByDescription(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("LastChangedByUserDescription")) {
                final Object value = cloudSdkValues.remove("LastChangedByUserDescription");
                if ((value == null)||(!value.equals(getDraftLastChangedByDescription()))) {
                    setDraftLastChangedByDescription(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("InProcessByUserDescription")) {
                final Object value = cloudSdkValues.remove("InProcessByUserDescription");
                if ((value == null)||(!value.equals(getDraftInProcessByDescription()))) {
                    setDraftInProcessByDescription(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return S4CreateCdsMetadataService.DEFAULT_SERVICE_PATH;
    }

}
