
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>EntityControl</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class EntityControl
    extends VdmComplex<EntityControl>
{

    @Getter
    private final String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.EntityControl";
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Deletable</b></p>
     * 
     * @return
     *     The deletable contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("Deletable")
    private java.lang.Boolean deletable;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<EntityControl> DELETABLE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<EntityControl>(EntityControl.class, "Deletable");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Updatable</b></p>
     * 
     * @return
     *     The updatable contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("Updatable")
    private java.lang.Boolean updatable;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<EntityControl> UPDATABLE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<EntityControl>(EntityControl.class, "Updatable");

    @Nonnull
    @Override
    public Class<EntityControl> getType() {
        return EntityControl.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("Deletable", getDeletable());
        cloudSdkValues.put("Updatable", getUpdatable());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("Deletable")) {
                final Object value = cloudSdkValues.remove("Deletable");
                if ((value == null)||(!value.equals(getDeletable()))) {
                    setDeletable(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("Updatable")) {
                final Object value = cloudSdkValues.remove("Updatable");
                if ((value == null)||(!value.equals(getUpdatable()))) {
                    setUpdatable(((java.lang.Boolean) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Deletable</b></p>
     * 
     * @param deletable
     *     The deletable to set.
     */
    public void setDeletable(
        @Nullable
        final java.lang.Boolean deletable) {
        rememberChangedField("Deletable", this.deletable);
        this.deletable = deletable;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Updatable</b></p>
     * 
     * @param updatable
     *     The updatable to set.
     */
    public void setUpdatable(
        @Nullable
        final java.lang.Boolean updatable) {
        rememberChangedField("Updatable", this.updatable);
        this.updatable = updatable;
    }

}
