
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.util.LinkedList;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>SAP__Message</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class SAP__Message
    extends VdmComplex<SAP__Message>
{

    @Getter
    private final java.lang.String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.SAP__Message";
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>code</b></p>
     * 
     * @return
     *     The code contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("code")
    private java.lang.String code;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message> CODE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message>(SAP__Message.class, "code");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>message</b></p>
     * 
     * @return
     *     The message contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("message")
    private java.lang.String message;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message> MESSAGE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message>(SAP__Message.class, "message");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>target</b></p>
     * 
     * @return
     *     The target contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("target")
    private java.lang.String target;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message> TARGET = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message>(SAP__Message.class, "target");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>additionalTargets</b></p>
     * 
     * @return
     *     The additionalTargets contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("additionalTargets")
    private java.util.Collection<java.lang.String> additionalTargets;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Collection<SAP__Message, java.lang.String> ADDITIONAL_TARGETS = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Collection<SAP__Message, java.lang.String>(SAP__Message.class, "additionalTargets", java.lang.String.class);
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>transition</b></p>
     * 
     * @return
     *     The transition contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("transition")
    private java.lang.Boolean transition;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<SAP__Message> TRANSITION = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<SAP__Message>(SAP__Message.class, "transition");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>numericSeverity</b></p>
     * 
     * @return
     *     The numericSeverity contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("numericSeverity")
    private Short numericSeverity;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericInteger<SAP__Message> NUMERIC_SEVERITY = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.NumericInteger<SAP__Message>(SAP__Message.class, "numericSeverity");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>longtextUrl</b></p>
     * 
     * @return
     *     The longtextUrl contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("longtextUrl")
    private java.lang.String longtextUrl;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message> LONGTEXT_URL = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<SAP__Message>(SAP__Message.class, "longtextUrl");

    @Nonnull
    @Override
    public Class<SAP__Message> getType() {
        return SAP__Message.class;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("code", getCode());
        cloudSdkValues.put("message", getMessage());
        cloudSdkValues.put("target", getTarget());
        cloudSdkValues.put("additionalTargets", getAdditionalTargets());
        cloudSdkValues.put("transition", getTransition());
        cloudSdkValues.put("numericSeverity", getNumericSeverity());
        cloudSdkValues.put("longtextUrl", getLongtextUrl());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("code")) {
                final Object value = cloudSdkValues.remove("code");
                if ((value == null)||(!value.equals(getCode()))) {
                    setCode(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("message")) {
                final Object value = cloudSdkValues.remove("message");
                if ((value == null)||(!value.equals(getMessage()))) {
                    setMessage(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("target")) {
                final Object value = cloudSdkValues.remove("target");
                if ((value == null)||(!value.equals(getTarget()))) {
                    setTarget(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("additionalTargets")) {
                final Object value = cloudSdkValues.remove("additionalTargets");
                if (value instanceof Iterable) {
                    final LinkedList<java.lang.String> additionalTargets = new LinkedList<java.lang.String>();
                    for (Object item: ((Iterable<?> ) value)) {
                        additionalTargets.add(((java.lang.String) item));
                    }
                    setAdditionalTargets(additionalTargets);
                }
            }
            if (cloudSdkValues.containsKey("transition")) {
                final Object value = cloudSdkValues.remove("transition");
                if ((value == null)||(!value.equals(getTransition()))) {
                    setTransition(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("numericSeverity")) {
                final Object value = cloudSdkValues.remove("numericSeverity");
                if ((value == null)||(!value.equals(getNumericSeverity()))) {
                    setNumericSeverity(((Short) value));
                }
            }
            if (cloudSdkValues.containsKey("longtextUrl")) {
                final Object value = cloudSdkValues.remove("longtextUrl");
                if ((value == null)||(!value.equals(getLongtextUrl()))) {
                    setLongtextUrl(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>code</b></p>
     * 
     * @param code
     *     The code to set.
     */
    public void setCode(
        @Nullable
        final java.lang.String code) {
        rememberChangedField("code", this.code);
        this.code = code;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>message</b></p>
     * 
     * @param message
     *     The message to set.
     */
    public void setMessage(
        @Nullable
        final java.lang.String message) {
        rememberChangedField("message", this.message);
        this.message = message;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>target</b></p>
     * 
     * @param target
     *     The target to set.
     */
    public void setTarget(
        @Nullable
        final java.lang.String target) {
        rememberChangedField("target", this.target);
        this.target = target;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>additionalTargets</b></p>
     * 
     * @param additionalTargets
     *     The additionalTargets to set.
     */
    public void setAdditionalTargets(
        @Nullable
        final java.util.Collection<java.lang.String> additionalTargets) {
        rememberChangedField("additionalTargets", this.additionalTargets);
        this.additionalTargets = additionalTargets;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>transition</b></p>
     * 
     * @param transition
     *     The transition to set.
     */
    public void setTransition(
        @Nullable
        final java.lang.Boolean transition) {
        rememberChangedField("transition", this.transition);
        this.transition = transition;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>numericSeverity</b></p>
     * 
     * @param numericSeverity
     *     The numericSeverity to set.
     */
    public void setNumericSeverity(
        @Nullable
        final Short numericSeverity) {
        rememberChangedField("numericSeverity", this.numericSeverity);
        this.numericSeverity = numericSeverity;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>longtextUrl</b></p>
     * 
     * @param longtextUrl
     *     The longtextUrl to set.
     */
    public void setLongtextUrl(
        @Nullable
        final java.lang.String longtextUrl) {
        rememberChangedField("longtextUrl", this.longtextUrl);
        this.longtextUrl = longtextUrl;
    }

}
