
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>zc_genddls_pCbAControl</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class zc_genddls_pCbAControl
    extends VdmComplex<zc_genddls_pCbAControl>
{

    @Getter
    private final String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.zc_genddls_pCbAControl";
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>_log</b></p>
     * 
     * @return
     *     The _log contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("_log")
    private java.lang.Boolean _log;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pCbAControl> _LOG = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pCbAControl>(zc_genddls_pCbAControl.class, "_log");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>_source</b></p>
     * 
     * @return
     *     The _source contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("_source")
    private java.lang.Boolean _source;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pCbAControl> _SOURCE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pCbAControl>(zc_genddls_pCbAControl.class, "_source");

    @Nonnull
    @Override
    public Class<zc_genddls_pCbAControl> getType() {
        return zc_genddls_pCbAControl.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("_log", get_log());
        cloudSdkValues.put("_source", get_source());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("_log")) {
                final Object value = cloudSdkValues.remove("_log");
                if ((value == null)||(!value.equals(get_log()))) {
                    set_log(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("_source")) {
                final Object value = cloudSdkValues.remove("_source");
                if ((value == null)||(!value.equals(get_source()))) {
                    set_source(((java.lang.Boolean) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>_log</b></p>
     * 
     * @param _log
     *     The _log to set.
     */
    public void set_log(
        @Nullable
        final java.lang.Boolean _log) {
        rememberChangedField("_log", this._log);
        this._log = _log;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>_source</b></p>
     * 
     * @param _source
     *     The _source to set.
     */
    public void set_source(
        @Nullable
        final java.lang.Boolean _source) {
        rememberChangedField("_source", this._source);
        this._source = _source;
    }

}
