
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>zc_genddls_pOperationControl</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class zc_genddls_pOperationControl
    extends VdmComplex<zc_genddls_pOperationControl>
{

    @Getter
    private final String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.zc_genddls_pOperationControl";
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>activeCDS</b></p>
     * 
     * @return
     *     The activeCDS contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("activeCDS")
    private java.lang.Boolean activeCDS;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pOperationControl> ACTIVE_CDS = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pOperationControl>(zc_genddls_pOperationControl.class, "activeCDS");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Edit</b></p>
     * 
     * @return
     *     The edit contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("Edit")
    private java.lang.Boolean edit;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pOperationControl> EDIT = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Boolean<zc_genddls_pOperationControl>(zc_genddls_pOperationControl.class, "Edit");

    @Nonnull
    @Override
    public Class<zc_genddls_pOperationControl> getType() {
        return zc_genddls_pOperationControl.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("activeCDS", getActiveCDS());
        cloudSdkValues.put("Edit", getEdit());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("activeCDS")) {
                final Object value = cloudSdkValues.remove("activeCDS");
                if ((value == null)||(!value.equals(getActiveCDS()))) {
                    setActiveCDS(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("Edit")) {
                final Object value = cloudSdkValues.remove("Edit");
                if ((value == null)||(!value.equals(getEdit()))) {
                    setEdit(((java.lang.Boolean) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>activeCDS</b></p>
     * 
     * @param activeCDS
     *     The activeCDS to set.
     */
    public void setActiveCDS(
        @Nullable
        final java.lang.Boolean activeCDS) {
        rememberChangedField("activeCDS", this.activeCDS);
        this.activeCDS = activeCDS;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Edit</b></p>
     * 
     * @param edit
     *     The edit to set.
     */
    public void setEdit(
        @Nullable
        final java.lang.Boolean edit) {
        rememberChangedField("Edit", this.edit);
        this.edit = edit;
    }

}
