
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>ZSGEN_DDLS_SOURCE_LIST</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class ZSGEN_DDLS_SOURCE_LIST
    extends VdmComplex<ZSGEN_DDLS_SOURCE_LIST>
{

    @Getter
    private final java.lang.String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.ZSGEN_DDLS_SOURCE_LIST";
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>VIEWNAME</b></p>
     * 
     * @return
     *     The vIEWNAME contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("VIEWNAME")
    private java.lang.String vIEWNAME;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST> VIEWNAME = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST>(ZSGEN_DDLS_SOURCE_LIST.class, "VIEWNAME");
    /**
     * Constraints: Not nullable, Maximum length: 60 <p>Original property name from the Odata EDM: <b>VIEWDESC</b></p>
     * 
     * @return
     *     The vIEWDESC contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("VIEWDESC")
    private java.lang.String vIEWDESC;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST> VIEWDESC = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST>(ZSGEN_DDLS_SOURCE_LIST.class, "VIEWDESC");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>REFERENCE</b></p>
     * 
     * @return
     *     The rEFERENCE contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("REFERENCE")
    private java.lang.String rEFERENCE;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST> REFERENCE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST>(ZSGEN_DDLS_SOURCE_LIST.class, "REFERENCE");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SOURCECODE</b></p>
     * 
     * @return
     *     The sOURCECODE contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("SOURCECODE")
    private java.lang.String sOURCECODE;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST> SOURCECODE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_SOURCE_LIST>(ZSGEN_DDLS_SOURCE_LIST.class, "SOURCECODE");

    @Nonnull
    @Override
    public Class<ZSGEN_DDLS_SOURCE_LIST> getType() {
        return ZSGEN_DDLS_SOURCE_LIST.class;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("VIEWNAME", getVIEWNAME());
        cloudSdkValues.put("VIEWDESC", getVIEWDESC());
        cloudSdkValues.put("REFERENCE", getREFERENCE());
        cloudSdkValues.put("SOURCECODE", getSOURCECODE());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("VIEWNAME")) {
                final Object value = cloudSdkValues.remove("VIEWNAME");
                if ((value == null)||(!value.equals(getVIEWNAME()))) {
                    setVIEWNAME(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("VIEWDESC")) {
                final Object value = cloudSdkValues.remove("VIEWDESC");
                if ((value == null)||(!value.equals(getVIEWDESC()))) {
                    setVIEWDESC(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("REFERENCE")) {
                final Object value = cloudSdkValues.remove("REFERENCE");
                if ((value == null)||(!value.equals(getREFERENCE()))) {
                    setREFERENCE(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("SOURCECODE")) {
                final Object value = cloudSdkValues.remove("SOURCECODE");
                if ((value == null)||(!value.equals(getSOURCECODE()))) {
                    setSOURCECODE(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>VIEWNAME</b></p>
     * 
     * @param vIEWNAME
     *     The vIEWNAME to set.
     */
    public void setVIEWNAME(
        @Nullable
        final java.lang.String vIEWNAME) {
        rememberChangedField("VIEWNAME", this.vIEWNAME);
        this.vIEWNAME = vIEWNAME;
    }

    /**
     * Constraints: Not nullable, Maximum length: 60 <p>Original property name from the Odata EDM: <b>VIEWDESC</b></p>
     * 
     * @param vIEWDESC
     *     The vIEWDESC to set.
     */
    public void setVIEWDESC(
        @Nullable
        final java.lang.String vIEWDESC) {
        rememberChangedField("VIEWDESC", this.vIEWDESC);
        this.vIEWDESC = vIEWDESC;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>REFERENCE</b></p>
     * 
     * @param rEFERENCE
     *     The rEFERENCE to set.
     */
    public void setREFERENCE(
        @Nullable
        final java.lang.String rEFERENCE) {
        rememberChangedField("REFERENCE", this.rEFERENCE);
        this.rEFERENCE = rEFERENCE;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SOURCECODE</b></p>
     * 
     * @param sOURCECODE
     *     The sOURCECODE to set.
     */
    public void setSOURCECODE(
        @Nullable
        final java.lang.String sOURCECODE) {
        rememberChangedField("SOURCECODE", this.sOURCECODE);
        this.sOURCECODE = sOURCECODE;
    }

}
