
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.20.0
 */

package customer.ai2code.model.s4.namespaces.s4createcdsmetadata;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmComplex;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>ZSGEN_DDLS_RESPONSE</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class ZSGEN_DDLS_RESPONSE
    extends VdmComplex<ZSGEN_DDLS_RESPONSE>
{

    @Getter
    private final java.lang.String odataType = "com.sap.gateway.srvd.zsrvd_genddls.v0001.ZSGEN_DDLS_RESPONSE";
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>PROJNAME</b></p>
     * 
     * @return
     *     The pROJNAME contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("PROJNAME")
    private java.lang.String pROJNAME;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> PROJNAME = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "PROJNAME");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UUID</b></p>
     * 
     * @return
     *     The uUID contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("UUID")
    private java.util.UUID uUID;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Guid<ZSGEN_DDLS_RESPONSE> UUID = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.Guid<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "UUID");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>REFERENCE</b></p>
     * 
     * @return
     *     The rEFERENCE contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("REFERENCE")
    private java.lang.String rEFERENCE;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> REFERENCE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "REFERENCE");
    /**
     * Constraints: Not nullable, Maximum length: 220 <p>Original property name from the Odata EDM: <b>MESSAGE</b></p>
     * 
     * @return
     *     The mESSAGE contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("MESSAGE")
    private java.lang.String mESSAGE;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> MESSAGE = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "MESSAGE");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>STATUS</b></p>
     * 
     * @return
     *     The sTATUS contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("STATUS")
    private java.lang.String sTATUS;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> STATUS = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "STATUS");
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @return
     *     The iD contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("ID")
    private java.lang.String iD;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> ID = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "ID");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V1</b></p>
     * 
     * @return
     *     The mESSAGE_V1 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("MESSAGE_V1")
    private java.lang.String mESSAGE_V1;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> M_E_S_S_A_G_E_V1 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "MESSAGE_V1");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V2</b></p>
     * 
     * @return
     *     The mESSAGE_V2 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("MESSAGE_V2")
    private java.lang.String mESSAGE_V2;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> M_E_S_S_A_G_E_V2 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "MESSAGE_V2");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V3</b></p>
     * 
     * @return
     *     The mESSAGE_V3 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("MESSAGE_V3")
    private java.lang.String mESSAGE_V3;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> M_E_S_S_A_G_E_V3 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "MESSAGE_V3");
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V4</b></p>
     * 
     * @return
     *     The mESSAGE_V4 contained in this {@link VdmComplex}.
     */
    @Nullable
    @ElementName("MESSAGE_V4")
    private java.lang.String mESSAGE_V4;
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE> M_E_S_S_A_G_E_V4 = new com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty.String<ZSGEN_DDLS_RESPONSE>(ZSGEN_DDLS_RESPONSE.class, "MESSAGE_V4");

    @Nonnull
    @Override
    public Class<ZSGEN_DDLS_RESPONSE> getType() {
        return ZSGEN_DDLS_RESPONSE.class;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("PROJNAME", getPROJNAME());
        cloudSdkValues.put("UUID", getUUID());
        cloudSdkValues.put("REFERENCE", getREFERENCE());
        cloudSdkValues.put("MESSAGE", getMESSAGE());
        cloudSdkValues.put("STATUS", getSTATUS());
        cloudSdkValues.put("ID", getID());
        cloudSdkValues.put("MESSAGE_V1", getMESSAGE_V1());
        cloudSdkValues.put("MESSAGE_V2", getMESSAGE_V2());
        cloudSdkValues.put("MESSAGE_V3", getMESSAGE_V3());
        cloudSdkValues.put("MESSAGE_V4", getMESSAGE_V4());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("PROJNAME")) {
                final Object value = cloudSdkValues.remove("PROJNAME");
                if ((value == null)||(!value.equals(getPROJNAME()))) {
                    setPROJNAME(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("UUID")) {
                final Object value = cloudSdkValues.remove("UUID");
                if ((value == null)||(!value.equals(getUUID()))) {
                    setUUID(((java.util.UUID) value));
                }
            }
            if (cloudSdkValues.containsKey("REFERENCE")) {
                final Object value = cloudSdkValues.remove("REFERENCE");
                if ((value == null)||(!value.equals(getREFERENCE()))) {
                    setREFERENCE(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MESSAGE")) {
                final Object value = cloudSdkValues.remove("MESSAGE");
                if ((value == null)||(!value.equals(getMESSAGE()))) {
                    setMESSAGE(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("STATUS")) {
                final Object value = cloudSdkValues.remove("STATUS");
                if ((value == null)||(!value.equals(getSTATUS()))) {
                    setSTATUS(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ID")) {
                final Object value = cloudSdkValues.remove("ID");
                if ((value == null)||(!value.equals(getID()))) {
                    setID(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MESSAGE_V1")) {
                final Object value = cloudSdkValues.remove("MESSAGE_V1");
                if ((value == null)||(!value.equals(getMESSAGE_V1()))) {
                    setMESSAGE_V1(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MESSAGE_V2")) {
                final Object value = cloudSdkValues.remove("MESSAGE_V2");
                if ((value == null)||(!value.equals(getMESSAGE_V2()))) {
                    setMESSAGE_V2(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MESSAGE_V3")) {
                final Object value = cloudSdkValues.remove("MESSAGE_V3");
                if ((value == null)||(!value.equals(getMESSAGE_V3()))) {
                    setMESSAGE_V3(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("MESSAGE_V4")) {
                final Object value = cloudSdkValues.remove("MESSAGE_V4");
                if ((value == null)||(!value.equals(getMESSAGE_V4()))) {
                    setMESSAGE_V4(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        return entityKey;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>PROJNAME</b></p>
     * 
     * @param pROJNAME
     *     The pROJNAME to set.
     */
    public void setPROJNAME(
        @Nullable
        final java.lang.String pROJNAME) {
        rememberChangedField("PROJNAME", this.pROJNAME);
        this.pROJNAME = pROJNAME;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UUID</b></p>
     * 
     * @param uUID
     *     The uUID to set.
     */
    public void setUUID(
        @Nullable
        final java.util.UUID uUID) {
        rememberChangedField("UUID", this.uUID);
        this.uUID = uUID;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>REFERENCE</b></p>
     * 
     * @param rEFERENCE
     *     The rEFERENCE to set.
     */
    public void setREFERENCE(
        @Nullable
        final java.lang.String rEFERENCE) {
        rememberChangedField("REFERENCE", this.rEFERENCE);
        this.rEFERENCE = rEFERENCE;
    }

    /**
     * Constraints: Not nullable, Maximum length: 220 <p>Original property name from the Odata EDM: <b>MESSAGE</b></p>
     * 
     * @param mESSAGE
     *     The mESSAGE to set.
     */
    public void setMESSAGE(
        @Nullable
        final java.lang.String mESSAGE) {
        rememberChangedField("MESSAGE", this.mESSAGE);
        this.mESSAGE = mESSAGE;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>STATUS</b></p>
     * 
     * @param sTATUS
     *     The sTATUS to set.
     */
    public void setSTATUS(
        @Nullable
        final java.lang.String sTATUS) {
        rememberChangedField("STATUS", this.sTATUS);
        this.sTATUS = sTATUS;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>ID</b></p>
     * 
     * @param iD
     *     The iD to set.
     */
    public void setID(
        @Nullable
        final java.lang.String iD) {
        rememberChangedField("ID", this.iD);
        this.iD = iD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V1</b></p>
     * 
     * @param mESSAGE_V1
     *     The mESSAGE_V1 to set.
     */
    public void setMESSAGE_V1(
        @Nullable
        final java.lang.String mESSAGE_V1) {
        rememberChangedField("MESSAGE_V1", this.mESSAGE_V1);
        this.mESSAGE_V1 = mESSAGE_V1;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V2</b></p>
     * 
     * @param mESSAGE_V2
     *     The mESSAGE_V2 to set.
     */
    public void setMESSAGE_V2(
        @Nullable
        final java.lang.String mESSAGE_V2) {
        rememberChangedField("MESSAGE_V2", this.mESSAGE_V2);
        this.mESSAGE_V2 = mESSAGE_V2;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V3</b></p>
     * 
     * @param mESSAGE_V3
     *     The mESSAGE_V3 to set.
     */
    public void setMESSAGE_V3(
        @Nullable
        final java.lang.String mESSAGE_V3) {
        rememberChangedField("MESSAGE_V3", this.mESSAGE_V3);
        this.mESSAGE_V3 = mESSAGE_V3;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>MESSAGE_V4</b></p>
     * 
     * @param mESSAGE_V4
     *     The mESSAGE_V4 to set.
     */
    public void setMESSAGE_V4(
        @Nullable
        final java.lang.String mESSAGE_V4) {
        rememberChangedField("MESSAGE_V4", this.mESSAGE_V4);
        this.mESSAGE_V4 = mESSAGE_V4;
    }

}
