---
spring:
  web:
    resources:
      static-locations: file:./app/
  config:
    activate:
      on-profile: default
  # sql:
  #   init:
  #     platform: h2
cds:
  remote:
    services:
      '[zsrvd_genbdef]':
        destination:
          name: zsrvd_genbdef
        type: odata-v4
      '[zsrvd_gentabl]':
        destination:
          name: zsrvd_gentabl
        type: odata-v4
      '[zsrvd_genddls]':
        destination:
          name: zsrvd_genddls
        http:
          service: zsrvd_genddls/0001
          csrf:
            enabled: true
          suffix: /sap/opu/odata4/sap/zsrvb_genddls/srvd/sap
        model: zsrvd_genddls
        type: odata-v4
      '[zsrvd_genclas]':
        destination:
          name: zsrvd_genclas
        type: odata-v4
      '[zsrvd_gensrvd]':
        destination:
          name: zsrvd_gensrvd
        http:
          service: zsrvd_gensrvd/0001
          csrf:
            enabled: true
          suffix: /sap/opu/odata4/sap/zsrvb_gensrvd/srvd/sap
        model: zsrvd_gensrvd
        type: odata-v4
  sql:
    hana:
      search:
        fuzzinessThreshold: 0.9
        fuzzy: true
---
spring:
  config.activate.on-profile: dev
  sql.init.platform: h2
  web.resources.static-locations: file:./app/
cds:
  data-source.auto-config.enabled: false

---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
logging:
  level:
    com:
      sap:
        cds:
          remote:
            odata: DEBUG
