spring:
  web:
    resources:
      static-locations: file:./app/
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
cds:
  data-source:
    auto-config:
      enabled: false
  remote:
    services:
      '[zsrvd_gensrvb]':
        destination:
          name: zsrvd_gensrvb
        type: odata-v4
      '[zsrvd_gentabl]':
        destination:
          name: zsrvd_gentabl
        type: odata-v4
      '[zsrvd_genddls]':
        destination:
          name: zsrvd_genddls
        http:
          service: zsrvd_genddls/0001
          csrf:
            enabled: true
          suffix: /sap/opu/odata4/sap/zsrvb_genddls/srvd/sap
        model: com.sap.gateway.srvd.zsrvd_genddls.v0001
        type: odata-v4
      '[zsrvd_gensrvd]':
        destination:
          name: zsrvd_gensrvd
        http:
          service: zsrvd_gensrvd/0001
          csrf:
            enabled: true
          suffix: /sap/opu/odata4/sap/zsrvb_gensrvd/srvd/sap
        model: com.sap.gateway.srvd.zsrvd_gensrvd.v0001
        type: odata-v4
  sql:
    hana:
      search:
        fuzzinessThreshold: 0.9
        fuzzy: true
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
