

/*
 * Amazon Bedrock Anthropic Claude Messages API
 * API for invoking Claude models through AWS Bedrock Runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.ai2code.model.aicore.claude;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.google.common.annotations.Beta;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Guardrail trace information for streaming
 */

@Beta// CHECKSTYLE:OFF
public class ConverseStreamTraceGuardrail 
// CHECKSTYLE:ON
{
  @JsonProperty("actionReason")
  private String actionReason;

  @JsonProperty("modelOutput")
  private List<String> modelOutput = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the actionReason of this {@link ConverseStreamTraceGuardrail} instance and return the same instance.
   *
   * @param actionReason  Reason for guardrail action
   * @return The same instance of this {@link ConverseStreamTraceGuardrail} class
   */
  @Nonnull public ConverseStreamTraceGuardrail actionReason( @Nullable final String actionReason) {
    this.actionReason = actionReason;
    return this;
  }

  /**
   * Reason for guardrail action
   * @return actionReason  The actionReason of this {@link ConverseStreamTraceGuardrail} instance.
   */
  @Nonnull
  public String getActionReason() {
    return actionReason;
  }

  /**
   * Set the actionReason of this {@link ConverseStreamTraceGuardrail} instance.
   *
   * @param actionReason  Reason for guardrail action
   */
  public void setActionReason( @Nullable final String actionReason) {
    this.actionReason = actionReason;
  }

  /**
   * Set the modelOutput of this {@link ConverseStreamTraceGuardrail} instance and return the same instance.
   *
   * @param modelOutput  Model output segments
   * @return The same instance of this {@link ConverseStreamTraceGuardrail} class
   */
  @Nonnull public ConverseStreamTraceGuardrail modelOutput( @Nullable final List<String> modelOutput) {
    this.modelOutput = modelOutput;
    return this;
  }
  /**
   * Add one modelOutput instance to this {@link ConverseStreamTraceGuardrail}.
   * @param modelOutputItem The modelOutput that should be added
   * @return The same instance of type {@link ConverseStreamTraceGuardrail}
   */
  @Nonnull public ConverseStreamTraceGuardrail addModelOutputItem( @Nonnull final String modelOutputItem) {
    if (this.modelOutput == null) {
      this.modelOutput = new ArrayList<>();
    }
    this.modelOutput.add(modelOutputItem);
    return this;
  }

  /**
   * Model output segments
   * @return modelOutput  The modelOutput of this {@link ConverseStreamTraceGuardrail} instance.
   */
  @Nonnull
  public List<String> getModelOutput() {
    return modelOutput;
  }

  /**
   * Set the modelOutput of this {@link ConverseStreamTraceGuardrail} instance.
   *
   * @param modelOutput  Model output segments
   */
  public void setModelOutput( @Nullable final List<String> modelOutput) {
    this.modelOutput = modelOutput;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ConverseStreamTraceGuardrail}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ConverseStreamTraceGuardrail} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ConverseStreamTraceGuardrail has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ConverseStreamTraceGuardrail} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( actionReason != null ) declaredFields.put("actionReason", actionReason);
    if( modelOutput != null ) declaredFields.put("modelOutput", modelOutput);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ConverseStreamTraceGuardrail} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ConverseStreamTraceGuardrail converseStreamTraceGuardrail = (ConverseStreamTraceGuardrail) o;
    return Objects.equals(this.cloudSdkCustomFields, converseStreamTraceGuardrail.cloudSdkCustomFields) &&
        Objects.equals(this.actionReason, converseStreamTraceGuardrail.actionReason) &&
        Objects.equals(this.modelOutput, converseStreamTraceGuardrail.modelOutput);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionReason, modelOutput, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ConverseStreamTraceGuardrail {\n");
    sb.append("    actionReason: ").append(toIndentedString(actionReason)).append("\n");
    sb.append("    modelOutput: ").append(toIndentedString(modelOutput)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

